etsin_finder/frontend/index.html, etsin_finder/frontend/js/components/navi.jsx, etsin_finder/frontend/js/components/secondnav.jsx, etsin_finder/frontend/js/components/userInfo.jsx, etsin_finder/frontend/js/index.jsx, etsin_finder/frontend/js/layout/footer.jsx, etsin_finder/frontend/js/layout/header.jsx, etsin_finder/frontend/locale/data.js, etsin_finder/frontend/locale/messages/js/components/navi.json, etsin_finder/frontend/locale/messages/js/components/secondnav.json, etsin_finder/frontend/locale/messages/js/components/userInfo.json, etsin_finder/frontend/locale/messages/js/layout/footer.json, etsin_finder/frontend/locale/messages/js/layout/header.json, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json, etsin_finder/frontend/scss/layout/_footer.scss
Header and Footer updated with translations
=> Cscetsin 68/base

etsin_finder/app_config.py, etsin_finder/elasticsearch/elasticsearch_service.py, etsin_finder/elasticsearch/es_dataset_data_model.py, etsin_finder/elasticsearch/resources/dataset_type_mapping.json, etsin_finder/elasticsearch/resources/metax_index_definition.json, etsin_finder/finder.py, etsin_finder/metax_api.py, etsin_finder/reindex_task.py, etsin_finder/views.py, rabbitmq_client.py
Connect to Metax(-test) RabbitMQ. Receive messages and display them in console.
=> CSCETSIN-95 RabbitMQ connect

etsin_finder/frontend/__tests__/elasticquery.test.jsx, etsin_finder/frontend/__tests__/sortResults.test.jsx, etsin_finder/frontend/js/components/search/filterResults/filterItem.jsx, etsin_finder/frontend/js/components/search/resultslist/index.jsx, etsin_finder/frontend/js/components/search/sortResults/index.jsx, etsin_finder/frontend/js/stores/view/elasticquery.js, etsin_finder/frontend/locale/translations.js, etsin_finder/frontend/scss/components/_loader.scss
Sorting component now functional.
Can sort by best match, date ascending and date descending.
=> CSCETSIN-120: ordering

etsin_finder/frontend/js/components/dataset/content.jsx, etsin_finder/frontend/js/components/dataset/description.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/general/label.jsx
Removed citation from harvested datasets, improved label logic for harvested, deprecated and  cumulative.
=> Cscetsin 179 harvested no citation

etsin_finder/email_utils.py, etsin_finder/frontend/js/components/dataset/description.jsx, etsin_finder/frontend/webpack.config.js, etsin_finder/resources.py
Contact form is not shown for harvested datasets. Contact API disallows sending mail regarding harvested datasets.
Also one unrelated change to fix broken npm watch.
=> CSCETSIN-188: no contact when harvested

etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx, etsin_finder/frontend/js/components/search/filterResults/index.jsx, etsin_finder/frontend/js/stores/view/elasticquery.js
Adds facet filters for infrastructure, project and file type on search result page. Note that this feature changes both etsin-finder and etsin-finder-search. The changes should be reviewed together.
=> CSCETSIN-134 new facet filters

etsin_finder/frontend/__tests__/getIdentifierFromQuery.test.jsx, etsin_finder/frontend/js/components/dataset/description.jsx, etsin_finder/frontend/js/components/dataset/downloads/index.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/dataset/versionChanger.jsx, etsin_finder/frontend/js/components/general/button.jsx, etsin_finder/frontend/js/components/search/index.jsx, etsin_finder/frontend/js/components/search/resultslist/index.jsx, etsin_finder/frontend/js/components/search/resultslist/listItem.jsx, etsin_finder/frontend/js/components/search/searchBar.jsx, etsin_finder/frontend/js/stores/view/datasetquery.js, etsin_finder/frontend/js/stores/view/elasticquery.js, etsin_finder/frontend/js/utils/getIdentifierFromQuery.jsx, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json, etsin_finder/metax_api.py
Switched dataset page url to use identifier and not preferred_identifier.
Removed straight redirect to dataset page if searching with a pid. Now it lists results on search page.
=> CSCETSIN-199: url to catalog record identifier

etsin_finder/frontend/js/components/dataset/data/idaResources/index.jsx, etsin_finder/frontend/js/components/dataset/data/info.jsx, etsin_finder/frontend/js/components/dataset/data/tableItem.jsx, etsin_finder/frontend/js/components/general/button.jsx, etsin_finder/frontend/stories/index.js
Also:
- added description on hover to said buttons.
- setup ida resources ready for download_urls.
- fixed problem with button theme colorchecker
=> fixed info modal button urls.

.gitignore, etsin_finder/frontend/js/components/dataset/contact/contactForm.jsx, etsin_finder/frontend/js/components/dataset/contact/index.jsx, etsin_finder/frontend/js/components/dataset/description.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/general/select.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/frontend/stories/index.js
- fixed errors with form validation breaking message modal.
- added text message modal, to guide users to send messages concerning access rights to the curator. (only visible if dataset is a rems dataset)
=> CSCETSIN-226: rems access

etsin_finder/frontend/js/components/errorpage/index.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
=> Cscetsin 232 error message

etsin_finder/frontend/js/components/frontpage/keyValues.jsx, etsin_finder/frontend/js/components/general/navigation/mobileNavi.jsx, etsin_finder/frontend/js/components/general/navigation/settings.jsx, etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx
- added queries for frontpage values
- if one of queries fail => hide keyvalues box
- two queries (total amount of datasets + aggragations)
- also temporarily redirect add more button to fairdata.fi
also CSCETSIN-234: changed facet text 'luoja' to 'tekijä'
=> CSCETSIN-235: frontpage values

etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/license.jsx, etsin_finder/frontend/js/components/dataset/sidebar/sidebarItem.jsx, etsin_finder/frontend/js/components/general/popup.jsx, etsin_finder/frontend/stories/index.js
- made some sidebar layout changes to allow overflow
- Added info button to licenses for more detailed information
- Added new popup alignment rules
=> CSCETSIN-240: added license info popup to all licenses

etsin_finder/frontend/js/components/dataset/accessRights.jsx, etsin_finder/frontend/js/components/dataset/data/idaResources/index.jsx, etsin_finder/frontend/js/components/dataset/data/info.jsx, etsin_finder/frontend/js/components/dataset/data/table.jsx, etsin_finder/frontend/js/components/dataset/description.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/dataset/people/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/sidebarItem.jsx, etsin_finder/frontend/js/components/dataset/versionChanger.jsx, etsin_finder/frontend/js/components/frontpage/keyValues.jsx, etsin_finder/frontend/js/components/general/announcer.jsx, etsin_finder/frontend/js/components/general/popup.jsx, etsin_finder/frontend/js/components/general/showMore.jsx, etsin_finder/frontend/js/utils/createTree.jsx, etsin_finder/frontend/js/utils/sizeParse.jsx
- Sidebar breaking due to`div` inside `p`
- Dataset notice bar not displaying deleted/deprecated message
- Data tab breaking on deleted/deprecated datasets, due to no file.details available
- Added markdown styling because `pre` and `code` blocks overflow content.
- Removed unneccessary console.logs
=> [FIX] Small UI problems

etsin_finder/frontend/js/components/dataset/sidebar/citation.jsx, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/license.jsx
- Added theme keywords to sidebar
- Fixed citation unique key error adn other key issues
=> CSCETSIN-253: theme keywords

etsin_finder/frontend/js/components/dataset/data/idaResources/index.jsx, etsin_finder/frontend/js/components/dataset/data/info.jsx, etsin_finder/frontend/js/components/dataset/people/person.jsx, etsin_finder/frontend/js/components/dataset/sidebar/citation.jsx, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/license.jsx, etsin_finder/frontend/js/components/dataset/sidebar/sidebarItem.jsx
Added spatial coverage to sidebar
Currently displayed as:
`{place_uri}, {geographic_name};`
if no place_uri available
`{geographic_name};`
=> Cscetsin 254 spatial sidebar

etsin_finder/frontend/__tests__/fileIcon.test.jsx, etsin_finder/frontend/js/components/dataset/availableTimestamp.jsx, etsin_finder/frontend/js/components/dataset/data/externalResources/index.jsx, etsin_finder/frontend/js/components/dataset/data/fileIcon.jsx, etsin_finder/frontend/js/components/dataset/data/idaResources/index.jsx, etsin_finder/frontend/js/components/dataset/data/info.jsx, etsin_finder/frontend/js/components/dataset/data/tableItem.jsx, etsin_finder/frontend/js/stores/view/datasetquery.js, etsin_finder/frontend/js/utils/propTypes.jsx, etsin_finder/metax_api.py, etsin_finder/resources.py
- refactored dataset data table code
- added better PropTypes
- added support for file_fields and directory_fields. Queries now return only specified fields.
- **fixed data tab not showing described content when moving inside folders.**
=> CSCETSIN-241: query fields

etsin_finder/frontend/js/components/dataset/accessRights.jsx, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/general/navigation/loginButton.jsx, etsin_finder/frontend/js/components/general/noticeBar.jsx, etsin_finder/frontend/locale/english.js
- added restriction grounds to sidebar (replaces access_type if available)
- added restriction grounds also to popup modal when clicking access button
- changed sidebar title "Access rights statement" => "Access"
=> CSCETSIN-248: Restriction grounds

etsin_finder/frontend/js/components/dataset/index.jsx
- back button now always points to dataset page, and clears url.
- ⭐️back button won't redirect outside our domain
- ⭐️no url bugs
=> CSCETSIN-266: [FIX] language change bug, changed back button logic

etsin_finder/frontend/js/components/dataset/goToOriginal.jsx, etsin_finder/frontend/js/components/dataset/identifier.jsx, etsin_finder/frontend/js/components/general/navigation/mobileNavi.jsx, etsin_finder/frontend/js/components/general/navigation/settings.jsx
- updated a few links to open in new tab, most links already had this.
=> CSCETSIN-265: [ADD] links open in new tabs

etsin_finder/frontend/package.json, etsin_finder/metax_api.py
Fix package.json. Change metax api request headers and decide whether to verify SSL.
=> Merge from test to stable: v0.9.1-rc1

etsin_finder/download_api.py
Improve Download API error handling
=> Merge from test to stable: v0.9.2-rc1

etsin_finder/frontend/js/components/dataset/data/tableHeader.jsx, etsin_finder/frontend/js/components/dataset/data/tableItem.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
Disables download button after it has been clicked.
=> CSCETSIN-283: Indicate file download has begun

etsin_finder/frontend/js/components/dataset/agents/agent.jsx, etsin_finder/frontend/js/components/dataset/agents/index.jsx, etsin_finder/frontend/js/components/dataset/data/tableHeader.jsx, etsin_finder/frontend/js/components/dataset/data/tableItem.jsx, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/general/popup.jsx
* Removed errors from console
* Creator/Contributor popups have now z-index to display them also on top of the sidebar
* Display Agents only if they have name
* Display Agent as clickable only when it has something relevant to show in the popup
=> Merge from test to stable: v0.9.6-rc5

etsin_finder/frontend/js/components/dataset/content.jsx, etsin_finder/frontend/js/components/dataset/data/index.jsx, etsin_finder/frontend/js/components/dataset/description.jsx, etsin_finder/frontend/js/components/dataset/events/index.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/dataset/maps/index.jsx, etsin_finder/frontend/js/components/errorpage/index.jsx, etsin_finder/frontend/js/components/frontpage/index.jsx, etsin_finder/frontend/js/components/search/index.jsx, etsin_finder/frontend/js/stores/view/elasticquery.js, etsin_finder/frontend/js/utils/tracking/index.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/static/index.template.ejs
Added tracking to the following pages: frontpage, searchpage, datasetpage and errorpage.
Added search query tracking to searchpage. (In matomo can be found in "behaviour -> site search".
Removed initial pageview, because it fired 2x, also after frontpage mounted.
Added new utility "tracking". Provides functions to push new pages to matomo and also search queries.
=> Cscetsin 324: Matomo tracking

etsin_finder/frontend/js/components/qvain/description/fieldOfScienceField.jsx, etsin_finder/frontend/js/components/qvain/description/keywordsField.jsx, etsin_finder/frontend/js/components/qvain/description/otherIdentifierField.jsx, etsin_finder/frontend/js/components/qvain/general/card.jsx, etsin_finder/frontend/js/components/qvain/licenses/accessType.jsx, etsin_finder/frontend/js/components/qvain/licenses/licenses.jsx, etsin_finder/frontend/js/stores/view/qvain.js
Description field is not connected to Qvain state store yet
=> CSCETSIN-398: state management for the rest of the fields

etsin_finder/frontend/js/components/qvain/description/index.jsx, etsin_finder/frontend/js/components/qvain/general/section/index.jsx, etsin_finder/frontend/js/components/qvain/general/section/title.jsx, etsin_finder/frontend/js/components/qvain/licenses/index.jsx
Section title styled component shared for sections
=> CSCETSIN-398 Section styled components stub

etsin_finder/frontend/js/components/qvain/general/buttons.jsx, etsin_finder/frontend/js/components/qvain/general/card.jsx, etsin_finder/frontend/js/components/qvain/general/section/title.jsx, etsin_finder/frontend/js/components/qvain/participants/index.jsx
Also warning about using `for` instead of `htmlFor` fixed
=> CSCETSIN-398 common button styles moved to general components

etsin_finder/app_config.py
Changed yaml.load to non deprecated version.
=> CSCETSIN-411:

etsin_finder/frontend/__tests__/qvain.test.jsx, etsin_finder/frontend/js/components/qvain/files/externalFiles.jsx, etsin_finder/frontend/js/components/qvain/files/fileForm.jsx, etsin_finder/frontend/js/components/qvain/files/idaFilePicker.jsx, etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx, etsin_finder/frontend/js/components/qvain/general/buttons.jsx, etsin_finder/frontend/js/components/qvain/general/card.jsx, etsin_finder/frontend/js/components/qvain/general/form.jsx, etsin_finder/frontend/js/stores/view/qvain.js, etsin_finder/frontend/locale/english.js
External files/resources/links field below file picker
=> CSCETSIN-416 external resources

etsin_finder/frontend/js/components/general/keepAlive/index.jsx, etsin_finder/frontend/js/components/general/navigation/dropdownMenu.jsx, etsin_finder/frontend/js/components/general/navigation/mobileNavi.jsx, etsin_finder/frontend/js/components/general/navigation/settings.jsx
Add dataset button as a dropdown and extended idle session time to 8 hours
=> Cscetsin 417

etsin_finder/frontend/js/components/qvain/datasets/pagination.jsx, etsin_finder/frontend/js/components/qvain/files/externalFiles.jsx, etsin_finder/frontend/js/components/qvain/files/idaFilePicker.jsx, etsin_finder/frontend/js/components/qvain/licenses/accessType.jsx, etsin_finder/frontend/js/components/qvain/licenses/resctrictionGrounds.jsx, etsin_finder/frontend/js/components/qvain/participants/participantInfo.jsx, etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/js/stores/view/qvain.js
Fixes for bugs reported in 
- CSCETSIN-430
- CSCETSIN-431
- CSCETSIN-432
- CSCETSIN-433
- CSCETSIN-434
- CSCETSIN-435
=> Qvain Light bug fixes

etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx, etsin_finder/frontend/js/components/qvain/index.jsx, etsin_finder/frontend/js/components/qvain/licenses/accessType.jsx, etsin_finder/frontend/js/components/qvain/licenses/embargoExpires.jsx, etsin_finder/frontend/js/components/qvain/participants/participantTypeSelect.jsx, etsin_finder/frontend/js/components/qvain/utils/constants.js, etsin_finder/frontend/js/components/qvain/utils/date.js, etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/js/layout/content.jsx, etsin_finder/frontend/js/stores/view/qvain.js
Fixes for issues CSCETSIN-436, CSCETSIN-437, CSCETSIN-438, CSCETSIN-439, CSCETSIN-440 and CSCETSIN-441. Also fixes regressed bug CSCETSIN-434.
=> Qvain light fixes

etsin_finder/frontend/__tests__/qvain.test.jsx, etsin_finder/frontend/js/components/qvain/description/descriptionField.jsx, etsin_finder/frontend/js/components/qvain/description/keywordsField.jsx, etsin_finder/frontend/js/components/qvain/description/otherIdentifierField.jsx, etsin_finder/frontend/js/components/qvain/files/externalFileForm.jsx, etsin_finder/frontend/js/components/qvain/files/externalFiles.jsx, etsin_finder/frontend/js/components/qvain/files/index.jsx, etsin_finder/frontend/js/components/qvain/general/form.jsx, etsin_finder/frontend/js/components/qvain/participants/participantInfo.jsx, etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/js/stores/view/qvain.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, requirements.txt
Contains fixes for issues 
CSCETSIN-454
CSCETSIN-456
CSCETSIN-457
CSCETSIN-458
CSCETSIN-459
And an implementation for CSCETSIN-461
=> Qvain light bug fixes and improvements

etsin_finder/frontend/js/components/dataset/data/fileIcon.jsx, etsin_finder/frontend/js/components/dataset/maps/index.jsx
Noticed warnings about some font awesome icons and fixed the import issue.
=> Fix broken icons

etsin_finder/frontend/js/components/qvain/datasets/pagination.jsx, etsin_finder/frontend/js/components/qvain/datasets/table.jsx, etsin_finder/frontend/js/components/qvain/utils/auth.js, etsin_finder/frontend/js/stores/domain/auth.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/qvain_light_service.py
Fixes
- Too much pagination (486): use Math.ceil to determine page count
- Too few results per page (505): increased result limit from 5 to 20
- Showing oldest first (506): sort by latest modified
=> CSCETSIN-486 pagination related fixes

etsin_finder/frontend/js/components/qvain/description/keywordsField.jsx, etsin_finder/frontend/js/components/qvain/licenses/embargoExpires.jsx, etsin_finder/frontend/js/stores/view/language.js
Fixed
- Adding empty keywords by using commas
- Embargo expiration date displayed in wrong format (US format)
=> CSCETSIN-510 & CSCETSIN-511

etsin_finder/frontend/js/components/qvain/description/descriptionField.jsx, etsin_finder/frontend/js/components/qvain/description/keywordsField.jsx, etsin_finder/frontend/js/components/qvain/files/externalFiles.jsx, etsin_finder/frontend/js/components/qvain/files/index.jsx, etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx, etsin_finder/frontend/js/components/qvain/general/buttons.jsx, etsin_finder/frontend/js/components/qvain/general/card.jsx, etsin_finder/frontend/js/components/qvain/general/form.jsx, etsin_finder/frontend/js/components/qvain/licenses/embargoExpires.jsx, etsin_finder/frontend/js/components/qvain/participants/addedParticipants.jsx
- To improve the UI, the Edit and Delete buttons (found in components/qvain/general/buttons.jsx) have been moved to the right
- New styling for the buttons, both default and hover styling
- ContainerSubsectionBottom, new div, accounts for divs that shouldn't have a visible top border
- General border colors have been changed from #eceeef to #cccccc. See more info below.
=> CSCETSIN-534: Align buttons

etsin_finder/frontend/js/components/qvain/licenses/index.jsx
License card should be first card under Licenses and Rights.
=> CSCETSIN-535 license is the first field under Rights and Licenses

etsin_finder/qvain_light_resources.py, etsin_finder/qvain_light_utils.py
- Fix issue where `check_if_data_in_user_IDA_project` function did not
let user create empty or ATT datasets even though it should.
- Changed the function logic to return false if data not in user projects,
otherwise return True. So if files and directories are empty then it
returns True.
- Effects creating datasets with IDA files.
=> CSCETSIN-555: Fix permission check for creating dataset with IDA files.

etsin_finder/frontend/js/components/qvain/datasets/table.jsx
Update filtered upon delete, refresh after setState completes
=> CSCETSIN-554 dataset table refresh on delete

etsin_finder/frontend/__tests__/qvain.test.jsx, etsin_finder/frontend/js/components/qvain/files/externalFiles.jsx
- Rewrote the test for adding external resources to comply with the new external resource functionality
- Rewrite, test is now similar to how participants is tested
- Some warnings still present in tests (dsSidebarItem.test.jsx and authStore.test.jsx), but all tests passed
=> CSCETSIN-557: Fix frontend tests

etsin_finder/frontend/.eslintrc, etsin_finder/frontend/js/components/qvain/description/descriptionInfo.jsx, etsin_finder/frontend/js/components/qvain/description/index.jsx, etsin_finder/frontend/js/components/qvain/files/filesInfo.jsx, etsin_finder/frontend/js/components/qvain/files/index.jsx, etsin_finder/frontend/js/components/qvain/general/form.jsx, etsin_finder/frontend/js/components/qvain/general/tooltip.jsx, etsin_finder/frontend/js/components/qvain/licenses/index.jsx, etsin_finder/frontend/js/components/qvain/licenses/licensesInfo.jsx, etsin_finder/frontend/js/components/qvain/participants/index.jsx, etsin_finder/frontend/js/components/qvain/participants/participantsInfoTooltip.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json
Added the tooltip component to Qvain Light to be used as section info displayers.
The necessary info for the sections is **NOT** given in this PR, will be added in a seperate ticket when the texts and translations are given.
=> Cscetsin 538 add tooltips

etsin_finder/frontend/js/components/general/navigation/settings.jsx
- The issue is only due to mistake in fixing issues in test.
- Removed the import for the separator because it should not be used.
=> CSCETSIN-558: Fix issue with Qvain Light button.

etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
- Some functions where not given all attributes + added som checks if
arrays are empty.
- Now filesToMetax and directoriesToMetax are always used to properly
parse the files.
- Effects creating and editing IDA data catalog datasets.
=> CSCETSIN-561: Refactor the code to be used as intended.

etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/js/stores/view/qvain.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/qvain_light_dataset_schema.py, etsin_finder/qvain_light_utils.py
- Trying to open a dataset that didn't have any license caused an Error
that prevented from even going to the edit form. Fixed the issue and
now only IDA catalog records have license as mandatory as described
in the specifications.
- Added checks in editDataset and changed the frontend validation.
- Effects creating and editing datasets.
=> CSCETSIN-565: Fix problems opening datasets without license.

etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- Missing translation for error where no participants were added. Some other translations were missing.
- Added translations, small syntax & capitalization fixes.
=> CSCETSIN-570: Improve error messages

etsin_finder/frontend/js/components/qvain/participants/participantInfo.jsx, etsin_finder/frontend/js/stores/view/qvain.js
- Fix issue with parent org becoming mandatory for organizations.
- Fix bug in adding your own organization.
- Fix issues with participant mapping.
=> Cscetsin 572 Participant issues.

etsin_finder/frontend/js/stores/view/qvain.js
- There where still some object comparisons and object is empty checks
that where done wrong so they should be fixed.
- Created functions isObjectEmpty and isEqualObj to add consistency to
checks. Also improved debug logging to console.
- Effects editing datasets.
=> CSCETSIN-574: Fix bugs related to participant mapping.

etsin_finder/frontend/js/components/qvain/datasets/table.jsx, etsin_finder/frontend/js/components/qvain/description/descriptionField.jsx, etsin_finder/frontend/js/components/qvain/general/submitResponse.jsx
- Made language selection buttons accessible.
- Improved usability for screen readers when browsing the dataset table.
- Made link to Etsin in submit response accessible.
=> Cscetsin 423 improve accessibility

etsin_finder/frontend/js/components/dataset/sidebar/special/license.jsx
Added reading of licences that don't have title -field
=> Changed license visibility to Render()

etsin_finder/download_service.py, etsin_finder/frontend/js/components/dataset/data/table.jsx, etsin_finder/frontend/js/components/dataset/data/tableHeader.jsx, etsin_finder/frontend/js/components/dataset/data/tableItem.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- Added error handling to download component
- some changes to response headers that should help.
=> Cscetsin 504 download issues

etsin_finder/frontend/js/components/dataset/data/tableHeader.jsx, etsin_finder/frontend/js/components/dataset/data/tableItem.jsx
This will remove the changes done in CSCETSIN-504 and replaces those with plain window.open which should just-work-as-is.
=> CSCETSIN-683: Fixed broken download implementation on frontend.

etsin_finder/frontend/js/components/dataset/contact/index.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/special/project/index.jsx, etsin_finder/frontend/js/components/dataset/versionChanger.jsx, etsin_finder/frontend/js/components/dataset/versionselect.jsx, etsin_finder/frontend/js/components/general/hero.jsx, etsin_finder/frontend/js/components/general/modal.jsx, etsin_finder/frontend/js/components/search/filterResults/filterItem.jsx, etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx, etsin_finder/frontend/js/components/search/index.jsx, etsin_finder/frontend/js/components/search/pagination/index.jsx, etsin_finder/frontend/js/components/search/searchBar.jsx, etsin_finder/frontend/js/layout/header.jsx, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json
- Silences the warnings for componentWillReciveProps.
- Fixed the warnings for componentWillUpdate.
- Updated react-router-dom
=> Cscetsin 685 lifecycle hook warnings

etsin_finder/frontend/js/index.jsx, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json
- Added the package to better be abel to fix accessibility issues and to
avoid causing problems while developing new features.
- Added check that only imports it if the node env is in development.
- Only effects logging to the console in development environment.
=> Add react-axe an accessibility auditing tool.

etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- Some text had the wrong information so they needed to be changed.
- Changed the texts according to CSCFAIRMETA-98 jira ticket.
=> CSCFAIRMETA-98: Text changes.

etsin_finder/frontend/js/components/qvain/files/dataCatalog.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- Some of the text involving remote resources and datacatalog had mixed
terms that needed to me changed.
- Added better texts according to CSCFAIRMETA-99 jira ticket.
=> CSCFAIRMETA-99: Corrected texts.

.travis-deploy.sh, etsin_finder/frontend/__tests__/__snapshots__/filterSection.test.jsx.snap, etsin_finder/frontend/__tests__/filterSection.test.jsx, etsin_finder/frontend/js/components/search/filterResults/PasCheckBox.jsx, etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx, etsin_finder/frontend/js/components/search/index.jsx, etsin_finder/frontend/js/stores/view/elasticquery.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
Added the functionality to include PAS datasets to the result.
=> Cscfairmeta 92 pas dataset issues in etsin

etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- Added 'Reference' and 'Lähdeviite' to the citation / sitaatti string
- Simple text edit in the locale (language) files
=> CSCFAIRMETA-264: Text changes (citation/sitaatti)

etsin_finder/frontend/__tests__/access.test.jsx, etsin_finder/frontend/__tests__/rems.test.jsx, etsin_finder/frontend/js/components/dataset/REMSButton.jsx, etsin_finder/frontend/js/components/dataset/askForAccess.jsx, etsin_finder/frontend/js/stores/index.js, etsin_finder/frontend/js/stores/view/access.js, etsin_finder/frontend/js/stores/view/datasetquery.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/resources.py
Adding the frontend part to be able to test better.
=> Cscfairmeta 4 rems in frontend

etsin_finder/frontend/js/components/qvain/index.jsx, etsin_finder/qvain_light_resources.py, etsin_finder/qvain_light_utils.py
- Error handling for cases where the user has no IDA projects and tries to create a dataset with IDA files
- Added separate error handling functionality for this case ('IdaError')
- Small typo fix & text fixes
=> CSCFAIRMETA-350: Error handling when no IDA projects

etsin_finder/frontend/js/components/qvain/description/otherIdentifierField.jsx
- Changed other identifier text box's sample url from http://orcid.org/  --> http://doi.org/
=> CSCFAIRMETA-259: FIX: Change other identifier's example URL

etsin_finder/frontend/js/components/dataset/formatChanger.jsx
Bugfix: Make download button to return JSON instead of XML
for Metax JSON -format
Should not have side-effects
=> CSCFAIRMETA-424_Metax_JSON_button_showing_Metax_XML

etsin_finder/frontend/js/components/qvain/description/fieldOfScienceField.jsx, etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js, etsin_finder/frontend/js/stores/view/qvain.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/qvain_light_dataset_schema.py, etsin_finder/qvain_light_utils.py
This reverts commit 1d8e8293841b798ce24850f0e8867fe2f574fda0.
=> Revert "CSCFAIRMETA 411: Add multiple field of science (#423)"

etsin_finder/rems_service.py
- Dataset crashes if permission is restricted
- Added a feature switch to the get request code
=> CSCFAIRMETA-481: Prevent dataset from crashing (REMS)

etsin_finder/frontend/js/components/qvain/description/fieldOfScienceField.jsx, etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js, etsin_finder/frontend/js/stores/view/qvain.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/qvain_light_dataset_schema.py, etsin_finder/qvain_light_utils.py
By accepting this PR, user will be able to add multiple field of science values from drop down.
=> CSCFAIRMETA-411: ADD: field of science field to accept multiple values

etsin_finder/frontend/js/components/qvain/index.jsx, etsin_finder/frontend/js/components/qvain/licenses/accessType.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/qvain_light_resources.py, etsin_finder/qvain_light_service.py, etsin_finder/qvain_light_utils.py
* Help text for "permission required" access type
* Pass user information to Metax on dataset creation/update
=> CSCFAIRMETA-336: REMS changes

etsin_finder/frontend/js/components/qvain/description/fieldOfScienceField.jsx
- The page would crash of the user pressed the add field of science button
if no value was selected.
- Add check that does not accept empty values.
=> CSCFAIRMETA-488: Fix bug when empty fieldOfScience cause crash.

etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap, etsin_finder/frontend/__tests__/qvain.test.jsx, etsin_finder/frontend/js/components/qvain/datasets/table.jsx, etsin_finder/frontend/js/components/qvain/datasets/tablePasState.jsx, etsin_finder/frontend/js/components/qvain/utils/constants.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- Added a text description of the different PAS dataset preservation sates
to replace the color differentiate that was used earlier.
- Added tablePasState component that represents the PAs state for such
datasets.
=> CSCFAIRMETA-471: Add PAS status description to dataset table.

etsin_finder/frontend/js/components/dataset/maps/index.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- The map tab can be visible but empty, if certain map related parameters are defined, but not others
- Fix: If the map tab is visible, always display a table of all defined map parameters, even if the map isn't shown
=> CSCFAIRMETA-192: [FIX] Map tab empty

etsin_finder/frontend/__tests__/qvain.test.jsx, etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/package.json
* change useDoi validation to support refactored actors
* update yup to fix a bug that prevented the fixed validation from working
* add frontend test for useDoi validation
=> CSCFAIRMETA-560: Fix DOI validation

etsin_finder/frontend/js/components/qvain/temporalAndSpatial/spatial/form/SpatialArrayInput.jsx, etsin_finder/frontend/js/stores/view/qvain.spatials.js, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json
Looks to be related to spatial coverage ( CSCFAIRMETA-465 )
What was done (locally):
- git checkout test 
- git pull
- npm install uuid
... and the result is this commit.
=> CSCFAIRMETA-465: [FIX] Fix missing npm package (uuid)

etsin_finder/frontend/js/components/qvain/general/select.jsx, etsin_finder/frontend/js/stores/view/qvain.js, etsin_finder/frontend/js/utils/uniqueByKey.jsx
* Add selected infrastructure to array on submit
* Make infrastructure selection clearable
* Fix selected option for some multi-value fields not being initialized in editDataset()
=> CSCFAIRMETA-460: Infrastructure selection fixes

etsin_finder/download_service.py
- This issue might fix issues with folder downloads
- Fix variable reference
=> CSCFAIRMETA-728: [FIX] Folder downloads

etsin_finder/frontend/__tests__/qvain.test.jsx, etsin_finder/frontend/js/components/qvain/actors/modal/actorRoles.jsx, etsin_finder/frontend/js/components/qvain/actors/modal/roleCheckbox.jsx, etsin_finder/frontend/js/components/qvain/utils/formValidation.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- added validation for publisher
- removed special case validation of useDoi for publisher
=> CSCFAIRMETA-640 publisher marked as mandatory in all cases

etsin_finder/frontend/__tests__/qvain.test.jsx, etsin_finder/frontend/js/components/qvain/description/issuedDateField.jsx, etsin_finder/frontend/js/stores/view/qvain.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
* Disable issued date for published DOI datasets
* Update DOI texts
* Set changed=true when useDoi is toggled
=> CSCFAIRMETA-641: DOI issued date changes

etsin_finder/frontend/js/components/qvain/landingPage/box.jsx, etsin_finder/frontend/js/components/qvain/landingPage/description.jsx, etsin_finder/frontend/js/components/qvain/landingPage/image.jsx, etsin_finder/frontend/js/layout/content.jsx
* Small mobile style changes
* Remove big landing page login button
* Require exact match for the '/' path to show landing page
=> CSCFAIRMETA-745: Landing page style tweaks

etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap, etsin_finder/frontend/js/components/dataset/fairdataPasDatasetIcon.jsx, etsin_finder/frontend/js/components/qvain/datasets/tablePasState.jsx, etsin_finder/frontend/js/utils/constants.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
* Update English translations of PAS to DPS (Digital Preservation Service)
* Refactor TablePasState, fix crash on unknown state
=> CSCFAIRMETA-602: Update PAS translations to DPS

etsin_finder/frontend/package-lock.json
- Travis deployment build to test fails due to differences in package-lock.json after recent updates to package-lock.json
( https://github.com/CSCfi/etsin-finder/pull/581/files#diff-380da6b131c5f0694d67a81b084aef58a668759fc79cdc46be25dd572d55b379 )
- What was done:
1. git checkout test && git pull
2. In local env, npm prune && npm install --only=production
Result: this PR
=> CSCFAIRADM-409: [FIX] Update package-lock.json

etsin_finder/frontend/js/components/qvain/files/external/externalFileForm.jsx
- Remove syntax `InEdit { ... }` -> remote resources are functional
=> CSCFAIRMETA-761: [FIX] Remote resources crash

etsin_finder/app_config.py, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/qvain/files/external/externalFileForm.jsx
https://github.com/CSCfi/etsin-finder/releases/tag/v0.9.32-rc2
=> Merge test to stable v0.9.32-rc2

etsin_finder/frontend/js/components/qvain/files/cumulativeState.jsx
- Fixes toggling cumulative state
=> CSCFAIRMETA-786: [FIX] Cumulative state

etsin_finder/frontend/js/components/qvain/files/external/externalFileForm.jsx
https://github.com/CSCfi/etsin-finder/releases/tag/v0.9.32-rc3
This one commit here:
158640c Merge pull request #603 from CSCfi/CSCFAIRMETA-786-fix-cumulative …
... appeared because the PR CSCFAIRMETA-786 was merged using the 'Merge commit' strategy.
- This will not happen if you use merge strategy "Squash and merge"
=> Merge test to stable v0.9.32-rc3

etsin_finder/frontend/js/components/dataset/events/index.jsx
- Check identifier existence in render function
- Replace ID with '' if its not found
- Remove checkRelations() function
=> CSCFAIRMETA-726-crash-when-relation-has-no-identifier

etsin_finder/frontend/js/components/qvain/fields/description/issuedDate/index.jsx
Fix setDate function being undefined because identifier names have changed.
=> CSCFAIRMETA-796: Fix not being able to change issued date

etsin_finder/frontend/js/components/dataset/events/index.jsx, etsin_finder/frontend/js/components/qvain/views/landingPage/index.jsx, etsin_finder/frontend/js/layout/content.jsx, etsin_finder/frontend/js/stores/view/accessibility.js, etsin_finder/frontend/js/stores/view/language.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
- Add getLocation function to accessibility for cases  when location
is not known
- Call handleNavigation from language/toggleLang
-
=> CSCFAIRMETA-741-Changing-language-doesnt-update-window-title

AUTHORS, README.md
Also includes an update of authors and specification of repository contents (Etsin and Qvain).
=> CSCFAIRADM-424: [REF] Update links to Travis

etsin_finder/app_config.py, etsin_finder/common_resources_v2.py, etsin_finder/common_service_v2.py, etsin_finder/finder.py, etsin_finder/frontend/js/components/general/form.jsx, etsin_finder/frontend/js/components/general/tooltipClick.jsx, etsin_finder/frontend/js/layout/content.jsx, etsin_finder/frontend/js/stores/view/qvain/qvain.filesv1.js, etsin_finder/frontend/js/utils/constants.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/qvain_light_dataset_schema.py, etsin_finder/qvain_light_dataset_schema_v2.py, etsin_finder/qvain_light_resources.py, etsin_finder/qvain_light_resources_v2.py, etsin_finder/qvain_light_rpc.py, etsin_finder/qvain_light_rpc_v2.py, etsin_finder/qvain_light_service.py, etsin_finder/qvain_light_service_v2.py, etsin_finder/qvain_light_utils.py, etsin_finder/qvain_light_utils_v2.py, tests/test_qvain_light_schema.py
- New Travis (travis-ci.com) is now integrated into this repository
- This PR is for testing what happens when a new PR is created
- Also contains some refactoring of old syntax
=> CSCFAIRADM-424: Test branch for checking if the new Travis integration works

etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap, etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap, etsin_finder/frontend/js/components/qvain/fields/project/index.jsx, etsin_finder/frontend/js/components/qvain/fields/temporalAndSpatial/temporal/TemporalList.jsx, etsin_finder/frontend/js/components/qvain/views/editor/stickyHeader.jsx, etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx, etsin_finder/frontend/js/components/qvain/views/editor/submitResponse.jsx, etsin_finder/frontend/js/components/qvain/views/main/index.jsx, etsin_finder/frontend/js/stores/view/qvain/qvain.project.js, etsin_finder/frontend/js/stores/view/qvain/qvain.temporals.js
- Fix errors in v1 submit
- Fix project loading failing when some fields are missing
- If no English or Finnish name is found for project, fill value from some other translation
- Fix SubmitResponse becoming permanently closed
- Fix open-ended date range display and save
- Fix SubmitButtons not being disabled while submitting
=> CSCFAIRMETA-837: Project and SubmitButtons fixes

etsin_finder/frontend/js/components/dataset/formatChanger.jsx, etsin_finder/frontend/js/components/dataset/formatselect.jsx, etsin_finder/frontend/js/components/dataset/versionChanger.jsx, etsin_finder/frontend/js/components/dataset/versionselect.jsx
- Allows download of metadata
- Allows changing of version
=> CSCFAIRMETA-486-Etsin-buttons-in-Firefox

etsin_finder/frontend/js/stores/view/accessibility.js
- Related to https://github.com/CSCfi/etsin-finder/pull/638
=> CSCFAIRMETA-835: Fix error in search tab

etsin_finder/frontend/__tests__/qvain.apiv2.test.jsx, etsin_finder/frontend/js/stores/view/accessibility.js, etsin_finder/frontend/js/stores/view/qvain/index.js, etsin_finder/frontend/js/stores/view/qvain/qvain.submit.js
- https://github.com/CSCfi/etsin-finder/releases/tag/v0.9.34-rc2
- Merge style: **Create a merge commit**
=> Merge test to stable v0.9.34-rc2

etsin_finder/frontend/js/stores/domain/env.flags.js, etsin_finder/frontend/js/stores/domain/env.js
* Fix group override not being applied after reload
* Fix DOWNLOAD_API_V2 not using the .FRONTEND flag
=> CSCFAIRMETA-834: Feature flag bugfixes

etsin_finder/flags.py, etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap, etsin_finder/frontend/js/components/qvain/views/editor/dataset.jsx, etsin_finder/frontend/js/components/qvain/views/editor/submitButtons.jsx, etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV1.jsx, etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx, etsin_finder/frontend/js/components/qvain/views/main/index.jsx, etsin_finder/frontend/js/stores/domain/env.flags.js
* Toggled with the UI.BOTTOM_SUBMIT_BUTTONS flag
=> CSCFAIRMETA-812: Support having submit buttons at bottom of the editor

etsin_finder/frontend/js/components/qvain/general/input/stringArray.jsx
* Display validation error on next line after AddNewButton for StringArray fields like keywords
=> CSCFAIRMETA-842: Prevent errors from moving addition button

etsin_finder/authentication.py
- Error handling for cases where the user logs in through SSO without having IDA projects
=> CSCFAIRMETA-850: Fix login through SSO for users without IDA groups

etsin_finder/views/auth_views.py
=> CSCFAIRMETA-894: Fix Etsin login endpoint

etsin_finder/frontend/js/components/qvain/fields/licenses/embargoExpires.jsx, etsin_finder/frontend/js/components/qvain/fields/licenses/restrictionGrounds.jsx
* Setting embargo expiration date didn't work
* Clearing restriction grounds gave an error
=> CSCFAIRMETA-911: Access type bugs

etsin_finder/frontend/js/components/qvain/fields/licenses/embargoExpires.jsx, etsin_finder/frontend/js/components/qvain/fields/licenses/restrictionGrounds.jsx
https://github.com/CSCfi/etsin-finder/releases/tag/v0.9.35-rc2
=> Merge test to stable v0.9.35-rc2

etsin_finder/utils/qvain_utils.py
* Add missing check to Qvain check_dataset_edit_permission
=> CSCFAIRMETA-945: Fix server error when dataset does not exist

etsin_finder/frontend/__tests__/__testdata__/qvain.datasets.js, etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.datasets.a11y.test.jsx, etsin_finder/frontend/js/components/qvain/views/datasets/datasetGroup.jsx, etsin_finder/frontend/js/components/qvain/views/datasets/pagination.jsx, etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx, etsin_finder/frontend/js/stores/domain/auth.js, etsin_finder/frontend/js/stores/view/qvain/qvain.datasets.js
* jest-axe tests for
* Qvain datasets page
* "Remove dataset" modal
=> CSCFAIRMETA-924: Qvain datasets page accessibility tests

etsin_finder/frontend/__mocks__/imageMock.js, etsin_finder/frontend/__tests__/combined/general/a11y/footer.a11y.test.jsx, etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.header.a11y.test.jsx, etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.landingPage.a11y.test.jsx, etsin_finder/frontend/package.json
* Jest-axe tests for
* Qvain Frontpage
* Qvain Header
* Common Footer
* Add support for testing components that import images
=> CSCFAIRMETA-923: Qvain frontpage accessibility tests

etsin_finder/frontend/js/components/qvain/fields/project/FundingAgency.jsx, etsin_finder/frontend/js/components/qvain/fields/project/FundingOrganization.jsx, etsin_finder/frontend/js/components/qvain/fields/project/index.jsx
* Editing an existing project deleted its title, which crashed the component
* Fix translation errors
=> CSCFAIRMETA-967: Fix producer project bugs

etsin_finder/frontend/js/components/dataset/data/idaResourcesV2/errorMessage.jsx, etsin_finder/frontend/js/styles/globalStyles.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
* Add new texts to error messages
* Add links to maintenance page
=> CSCFAIRMETA-841: Update download service error messages

etsin_finder/frontend/js/components/header/index.jsx, etsin_finder/frontend/js/components/search/filterResults/clearFilters.jsx, etsin_finder/frontend/js/components/search/filterResults/filterItem.jsx, etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx, etsin_finder/frontend/js/components/search/filterResults/filterToggle.jsx, etsin_finder/frontend/js/components/search/searchBar.jsx
- search
- filters and unfilters
- clear filters
- create/ edit datasets button
=> Etsin interaction tracking

etsin_finder/frontend/js/components/qvain/views/datasets/dataset.jsx, etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx, etsin_finder/frontend/js/components/qvain/views/editor/submitButtonsV2.jsx
Qvain interaction tracking
- actions buttons in datasets view (Template, new_version, Revert, Delete)
- preview in etsin
- draft and publish
=> CSCFAIRMETA-960 Qvain interactions tracking added

etsin_finder/frontend/__tests__/components/componentTestHarness.jsx, etsin_finder/frontend/__tests__/components/general/qvain.brief.test.jsx, etsin_finder/frontend/__tests__/components/general/qvain.expand.test.jsx, etsin_finder/frontend/__tests__/components/general/qvain.tooltip.test.jsx, etsin_finder/frontend/js/components/qvain/general/section/tooltip.jsx
some tooltip refactor, tests for brief expand and tooltip, ComponentTestHarness
=> CSCFAIRMETA-884 tests for genral section

etsin_finder/frontend/__tests__/combined/etsin/a11y/citationModal.a11y.test.jsx, etsin_finder/frontend/__tests__/utils/cite.test.js, etsin_finder/frontend/js/components/dataset/citation/citationModal.jsx, etsin_finder/frontend/js/components/dataset/citation/cite/apa.js, etsin_finder/frontend/js/components/dataset/citation/cite/chicago.js, etsin_finder/frontend/js/components/dataset/citation/cite/citationBuilder.js, etsin_finder/frontend/js/components/dataset/citation/cite/index.js, etsin_finder/frontend/js/components/dataset/citation/cite/mla.js, etsin_finder/frontend/js/components/dataset/citation/cite/utils.js, etsin_finder/frontend/js/components/dataset/copyToClipboard.jsx, etsin_finder/frontend/js/components/dataset/identifier.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/general/errorBoundary.jsx, etsin_finder/frontend/js/components/general/modal.jsx, etsin_finder/frontend/js/components/general/tooltipHover.jsx, etsin_finder/frontend/js/stores/view/datasetquery.js, etsin_finder/frontend/js/stores/view/locale.js, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/utils/flags.py
* Citation modal for APA, Chicago and MLA
* Enable with setFlag('UI.CITATION_MODAL', true)
* Reuse functionality from identifier "Copy to clipboard" button
* Use current language by default in getValueTranslation
* Add/fix left/right position for TooltipHover
* Use ErrorBoundary in Modal to prevent modals from crashing entire app
=> CSCFAIRMETA-906: Citation modal

etsin_finder/frontend/__tests__/utils/cite.test.js, etsin_finder/frontend/js/components/dataset/citation/citationModal.jsx, etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
Take into account that dataset_version_set has the latest version first.
=> CSCFAIRMETA-906: Fix citation version numbering

etsin_finder/frontend/__tests__/components/componentTestHarness.jsx, etsin_finder/frontend/__tests__/components/qvain/qvain.subjectHeadings.test.jsx, etsin_finder/frontend/__tests__/stores/view/qvain.subjectHeadings.test.jsx
storeWrapper and getWrapper added to componentTestHarness
=> complete subjectHeadings tests added

etsin_finder/frontend/js/components/dataset/data/common/iconButton.jsx, etsin_finder/frontend/js/components/dataset/data/externalResources/index.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js
* Show remote object count in data tab
* Open remote links in new tab
* Fix "Go to the original source" button not working
=> CSCFAIRMETA-990: Show remote object count in data tab

etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json, etsin_finder/frontend/webpack.dev.js, etsin_finder/views/index_views.py
Adds `dev` script to run server with fast refresh. Requires `WEBPACK_DEV_PROXY: true` in app_config so the index page template gets rendered properly by the backend.
=> Configuration for React fast refresh

etsin_finder/frontend/__tests__/components/componentTestHarness.jsx, etsin_finder/frontend/__tests__/components/general/qvain.stringArray.test.jsx, etsin_finder/frontend/__tests__/components/qvain/qvain.datasets.table.test.jsx, etsin_finder/frontend/__tests__/components/qvain/qvain.datasets.test.jsx, etsin_finder/frontend/js/components/qvain/views/datasets/index.jsx, etsin_finder/frontend/js/components/qvain/views/datasets/table.jsx
=> partial datasets tests

etsin_finder/frontend/__tests__/stores/view/qvain.datasets.test.js
=> tests for qvain.datasets

etsin_finder/frontend/.eslintrc, etsin_finder/frontend/js/components/dataset/citation/citationButton.jsx, etsin_finder/frontend/js/components/dataset/identifier.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/dataset/sidebar/index.jsx, etsin_finder/frontend/js/components/general/button.jsx, etsin_finder/frontend/js/components/general/flaggedComponent.jsx, etsin_finder/frontend/locale/english.js, etsin_finder/frontend/locale/finnish.js, etsin_finder/frontend/package-lock.json, etsin_finder/frontend/package.json, etsin_finder/utils/flags.py
* Improve citation button styling
* Move citation button next to Identifier
* Rename flag `UI.CITATION_MODAL` -> `UI.CITATION`
* Install eslint-config-prettier to disable eslint rules that conflict with prettier
=> CSCFAIRMETA-1006: Move Etsin citation button

etsin_finder/frontend/.eslintrc, etsin_finder/frontend/js/app.jsx, etsin_finder/frontend/js/components/dataset/index.jsx, etsin_finder/frontend/js/components/general/modal.jsx, etsin_finder/frontend/js/index.jsx, etsin_finder/frontend/js/stores/domain/env.flags.js, etsin_finder/frontend/js/stores/domain/env.js, etsin_finder/frontend/package.json, etsin_finder/frontend/webpack.config.js, etsin_finder/frontend/webpack.dev.js, etsin_finder/frontend/webpack.prod.js
* Use BUILD instead of process.env.NODE_ENV
* BUILD defaults to process.env.NODE_ENV
=> CSCFAIRMETA-1025: Add BUILD env variable

etsin_finder/frontend/__tests__/utils/cite.test.js, etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
* List also top organization if publisher is a suborganization
* Trim whitespace before determining parts of name
=> CSCFAIRMETA-906: [FIX] Citation fixes

etsin_finder/frontend/__tests__/utils/cite.test.js, etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
https://github.com/CSCfi/etsin-finder/releases/tag/v0.9.40-rc1
=> Merge test to stable v0.9.40-rc1

etsin_finder/services/cr_service.py
Changed timeouts in cr_service were accidentally dropped when resolving conflicts
=> CSCFAIRMETA-1037: [FIX] Fix cr_service timeouts

etsin_finder/utils/qvain_utils.py, tests/basetest.py, tests/frontend_test_data.py, tests/test_qvain_utils.py
qvain utils hasn't changed except imports are different and few logs deleted.
=> CSCFAIRMETA-1118 tests for qvain utils

etsin_finder/resources/common_resources.py, etsin_finder/resources/etsin_resources.py, etsin_finder/resources/qvain_resources.py, etsin_finder/utils/utils.py
TOTAL_ITEM_LIMIT removed
slice_array_on_limit function removed since it's not used anymore
=> CSCFAIRMETA-1105 removal of TOTAL_ITEM_LIMIT

etsin_finder/frontend/__tests__/combined/qvain/qvain.regression.test.jsx, etsin_finder/frontend/__tests__/stores/view/qvain.spatial.test.js, etsin_finder/frontend/js/stores/view/qvain/qvain.spatials.js, etsin_finder/frontend/js/stores/view/qvain/qvain.usedEntities.js
- same bug happened with spatials/locations
=> CSCFAIRMETA-1120 new Used entities gets saved when the user cancels edited provenance

etsin_finder/app_config.py, etsin_finder/frontend/static/index.template.ejs, etsin_finder/frontend/webpack.config.js, etsin_finder/frontend/webpack.dev.js, etsin_finder/frontend/webpack.prod.js, etsin_finder/views/index_views.py
* Get matomo script from app_config MATOMO_URL instead of hardcoded url
* Remove unused Matomo-related .env variables from frontend config
=> CSCFAIRMETA-1135: Add MATOMO_URL to app_config

etsin_finder/resources/common_resources.py, etsin_finder/resources/download_resources.py, etsin_finder/services/common_service.py, tests/test_download.py
- get_directory renamed to get_directories
- get_directory_for_project renamed to get_directories_for_project
- get_directory_for_project_using_scope added to common_service
=> CSCFAIRMETA-1124 Total package size limit check added to Package creation

etsin_finder/frontend/__tests__/combined/qvain/qvain.test.jsx, etsin_finder/frontend/__tests__/utils/utils.handleSubmit.test.js, etsin_finder/frontend/js/components/qvain/fields/files/dataCatalog.jsx, etsin_finder/frontend/js/components/qvain/fields/files/external/externalFileForm.jsx, etsin_finder/frontend/js/components/qvain/fields/files/external/externalFiles.jsx, etsin_finder/frontend/js/components/qvain/utils/getReferenceData.js, etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js, etsin_finder/frontend/js/components/qvain/utils/select.js, etsin_finder/frontend/js/stores/view/qvain/index.js, etsin_finder/frontend/js/stores/view/qvain/qvain.dataCatalog.schemas.js, etsin_finder/frontend/js/stores/view/qvain/qvain.externalResources.js, etsin_finder/frontend/js/stores/view/qvain/qvain.field.js, etsin_finder/frontend/js/stores/view/qvain/qvain.resources.js, etsin_finder/schemas/qvain_dataset_schema.py, etsin_finder/schemas/qvain_dataset_schema_v2.py, etsin_finder/utils/qvain_utils.py, tests/frontend_test_data.py, tests/test_qvain_utils.py
* Save remote resources in Metax JSON format in frontend
* Move remote resources to a separate ExternalResources class
* Increase code reuse in remote resource components
=> CSCFAIRMETA-1132: Refactor saving remote resource

etsin_finder/frontend/__tests__/stores/view/qvain.project.test.js, etsin_finder/frontend/js/components/qvain/fields/project/FundingAgency.jsx, etsin_finder/frontend/js/components/qvain/fields/project/utils.jsx, etsin_finder/frontend/js/components/qvain/general/input/organizationSelect.jsx, etsin_finder/frontend/js/stores/view/qvain/qvain.project.js, etsin_finder/frontend/locale/english/qvain.project.js, etsin_finder/frontend/locale/finnish/qvain.project.js, etsin_finder/schemas/qvain_dataset_schema.py, tests/frontend_test_data.py
* Remove contributor type description from project funding agency
* Simplify funding agency form
* Don't save `definition` and `in_scheme` for contributor type
=> CSCFAIRMETA-1150: Remove contributor type description from project

.flake8, etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.datasetsV2.a11y.test.jsx, etsin_finder/frontend/__tests__/components/qvain/qvain.datasetsV2.tabs.test.jsx, etsin_finder/frontend/__tests__/stores/view/qvain.datasetsV2.tabs.test.js, etsin_finder/frontend/js/components/qvain/views/datasetsV2/index.jsx, etsin_finder/frontend/js/components/qvain/views/datasetsV2/tabs.jsx, etsin_finder/frontend/js/layout/content.jsx, etsin_finder/frontend/js/routes/index.jsx, etsin_finder/frontend/js/stores/index.js, etsin_finder/frontend/js/stores/view/qvain/qvain.datasetsV2.js, etsin_finder/frontend/js/stores/view/qvain/qvain.datasetsV2.tabs.js, etsin_finder/frontend/locale/english/qvain.datasets.js, etsin_finder/frontend/locale/finnish/qvain.datasets.js, etsin_finder/utils/flags.py
* Enable with flag UI.NEW_DATASETS_VIEW
* Features specific to the new view are implemented in QvainDatasetsV2 store
* Run formatter on flags.py
=> CSCFAIRMETA-1153: Tabs for new datasets view
