CSCfi/etsin-finder

etsin_finder/frontend/static/index.html

**rel="preload"** is a new feature what isn't currently supported by all browsers (https://caniuse.com/#search=preload). Preload allows asyncronously loading styles.
Switched to use media="none" to allow loading styles asyncronously. Media is set to all after the styles have been loaded, to display them in the dom.

Removed preload from link element. Added media=none.

---

etsin_finder/frontend/js/components/dataset/sidebar/index.jsx

In dataset view, if license has a somewhat reasonable URL (= starting with http(s)://), link license text to the URL.

CSCETSIN-185: Link license text

---

etsin_finder/frontend/js/components/frontpage/keyValues.jsx
etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx
etsin_finder/frontend/js/stores/view/elasticquery.js

**This feature changes both etsin-finder and etsin-finder-search**
Makes "number of projects" on front page more accurate and reduces number of duplicate items in "organization" and "project" facets on search results page. Doesn't make things perfect, but the improvement should be visible.
Under the hood, organization and project names are split into language-specific fields that always have the same amount of items. Items in *_fi prefer Finnish names whenever they're available, English works likewise. If preferred language is not available, another name is picked.
Search result page facets use these fields to ensure facet values are displayed in user interface language as much as possible.
Number of distinct English project names is displayed on front page.

CSCETSIN-237: Update organization and project name indexing

---

etsin_finder/frontend/__tests__/createDirTree.test.jsx
etsin_finder/frontend/js/utils/createTree.jsx

While creating a tree structure from the files and folders one folder did not have the empty children array. `children: []`. This was due to a bug in the code where it thought the folder specified was the last item in the tree and didn't add the children object. But then the next folder specified was inside that folder and it couldnt add itself inside the children folder.
Added a file.type check while initially creating the items in the tree structure.
`file.type !== 'dir'` then don't add children array. But if yes add the children array.
Removed unused code childAmount. It was not used and unnecessary due to `children.length`being also available.

Cscetsin 343 data tab bug

---

etsin_finder/frontend/js/utils/tracking/index.js

`process.env` is only available in backend while building but not in frontend.
function `isActive()` checks if _paq function has been defined.

[FIX] matomo not being active in production

---

etsin_finder/frontend/js/components/dataset/agent.jsx
etsin_finder/frontend/js/components/dataset/description.jsx
etsin_finder/frontend/js/components/dataset/events/index.jsx
etsin_finder/frontend/js/components/dataset/sidebar/index.jsx
etsin_finder/frontend/js/components/dataset/togglableAgentList.jsx
etsin_finder/frontend/stories/index.js
etsin_finder/frontend/stories/metaxRes.js

- Rename and relocate dataset/agents/index.jsx -> dataset/togglableAgentList.jsx and change its contents so that it now gets the agent(s) object as props and separately agent type.
- Relocate dataset/agents/agent.jsx -> dataset/agent.jsx
- Add agent popup for curator, rights_holder and publisher
- Add agent popup for provenance item's was_associated_with agent
- Add agent popup for is_output_of item's has_funding_agency agent

CSCETSIN-261

---

etsin_finder/frontend/js/components/qvain/files/projectSelector.jsx
etsin_finder/frontend/js/components/qvain/utils/object.js
etsin_finder/frontend/js/stores/view/qvain.js

Undefined values were breaking the rendering of files in IDA file picker's file hierarchy view. Use a "get or undefined" function to get the values safely.

CSCETSIN-463 files not being rendered in file picker

---

etsin_finder/frontend/js/components/qvain/files/externalFileForm.jsx
etsin_finder/frontend/js/components/qvain/files/externalFiles.jsx

Fix save bug in externalFileForm.jsx, where it was possible to save an invalid URL by clicking the Save button twice.
Implement invalid URL check also for the Edit button, found in externalFiles.jsx. URL check runs when trying to exit edit mode without first clicking "Save".

Cscetsin 472 fix invalid url

---

etsin_finder/frontend/js/components/qvain/files/externalFileForm.jsx

CSCETSIN-503: Fix use category dropdown
- In the use category dropdown, the selected use category was previously not visible. Furthermore, it was only possible to save the use category selection once.
- The use category dropdown is now updated correctly, using binary logic (boolean: isEditForm).
- Some syntax improvements (state: useCategories and const: lang) in externalFileForm.jsx
- The function handleChangeUse is now redundant, since its functionality is now handled directly in the useCategory dropdown's onChange event
- Functionality moved from handleChangeUse to onChange
- The boolean isEditForm is used to select the correct functionality in onChange

CSCETSIN-503: Fix use category dropdown

---

etsin_finder/frontend/js/components/qvain/participants/participantInfo.jsx

Fixes:
- Organization dropdown slowed down the entire browser tab
- When selecting and organization and then adding a custom one in participants, participant identifier field would retain its previous value and would stay disabled.

CSCETSIN-422 & CSCETSIN-509

---

etsin_finder/qvain_light_resources.py

- Check if the user preforming the edit is the same as the creator of
the dataset.
- Check from saml metadata if the user is the same as the
metadata_provider_user
- Changes effect EDIT operations only.

CSCETSIN-478: Add dataset permission check to edit operations.

---

etsin_finder/frontend/js/components/qvain/licenses/embargoExpires.jsx

- Removed the question mark icon (?), since it was deemed unnecessary to show it. Clicking it opens a navigation help window. 
- DatePicker is part of the imported library react-dates, developed by react-dates
- The question mark/help window is also a native library function. Found in the react-dates/SingleDatePicker library
- Turned off by using the hideKeyboardShortcutsPanel prop, inherent to the library
See demo of the library
http://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default

CSCETSIN-537: Remove ? icon

---

etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- Required date format is set to yyyy-mm-dd, in accordance with the ISO-8601 standard. However, since this is not the Finnish standard, date format instructions have now been added.
- Simple change text change, adding the required format example, both in Finnish and English
- The format example could potentially be added as the input placeholder instead, however, having it in the input label is probably better and easier to understand for the user, and it is always visible here.

CSCETSIN-536: Provide instructions for date format in Create Dataset Embargo

---

etsin_finder/frontend/js/components/qvain/datasets/table.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- Consistency improvement, simple renaming of:
1. Variable: name --> title
2. English variable value: 'Name' --> 'Title'
3. Finnish variable value: 'Nimi' --> 'Otsikko'

CSCETSIN-531: Rename 'name' column in Dataset list to 'title'

---

etsin_finder/frontend/js/components/qvain/description/descriptionField.jsx

The default language change is related to the input fields (title & description)
- Deemed necessary since more end users will probably want to select Finnish rather than English
- Simple switch of language variable values in descriptionField.jsx
- All previous code reused, no side effects
(This is not an app-wide language change, just a language change in the default title/description tab in Create Dataset)

CSCETSIN-533: Change default language choice in Create Dataset to Finnish

---

etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
etsin_finder/qvain_light_resources.py
etsin_finder/qvain_light_utils.py

- Added function to the backend that checks if the user belongs to the same projects that the IDA files or folders come from.
- Added the projectIdentifier to the data submitted to the backend.

Cscetsin 520 Check if user belongs to projects that data come from.

---

etsin_finder/frontend/js/stores/view/qvain.js

Fix use category always being Outcome Material even though specified to be different.

CSCETSIN-543 get use category for directory

---

etsin_finder/frontend/js/components/qvain/utils/formValidation.js

- Allow longer text in these fields to avoid errors where someone has
added longer text than Qvain Light allows and then is unable to edit
dataset.
- Altered the formValidation to accept longer `max` values.
- Changes have the side effect of possibly getting larger datasets to
handel.

CSCETSIN-541: Refactor form validation to accept longer titles, descriptions, keywords and participant fields.

---

etsin_finder/frontend/js/components/frontpage/index.jsx
etsin_finder/frontend/js/stores/domain/auth.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- To account for cases where a user has logged in through HAKA, but does not have a CSC account
- Display an error message, directing the user to create a CSC account for access.
- When the error message is closed by the user, their account is logged out.

CSCETSIN-524: Login without CSC account

---

etsin_finder/frontend/static/index.template.ejs

- Matomo is set up to track user visits and better understand what parts of the app are most used.
- Some older Matomo code was already present in index.template.ejs, though apparently unused. Rewrote some functionality.
- The Matomo functionality needs to be tested once these changes pushed to test.

CSCETSIN-420: Enable Matomo when in production

---

etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
etsin_finder/qvain_light_utils.py

- Added checks if previous files or directories are empty to handle it
and not cause error. Also send dir/files/ext as empty arrays instead
of undefined to help backend handle it.
- Check if empty before operations such as filter/map.
- Effects creating and editing datasets.

CSCETSIN-560: Fix problems with creating dataset.

---

etsin_finder/authentication.py
etsin_finder/frontend/js/components/frontpage/index.jsx
etsin_finder/frontend/js/stores/domain/auth.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js
etsin_finder/resources.py

- If the user tries to login with their CSC account and succeeds, but do not have a home organization set through sui.csc.fi, an error should be displayed.
- New backend requests, new error message modal, verificiation variables/logic and translation
- Both home organization name and id are retrieved from the backend. Verification through the home organization name, since HAKA accounts seem to have a home organization id (funet.fi).

CSCETSIN-525: Login without home organization

---

etsin_finder/frontend/js/components/qvain/utils/formValidation.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- Use category is a required field, and so must be validated
- Validation using string check, since the use category options are 7 preset strings
- Noticed possible general issue: Need to check field input error message displays for Finnish language

CSCETSIN-563: Validate external resource use category

---

etsin_finder/frontend/js/components/qvain/utils/formValidation.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- In order to post a dataset to the backend, a publisher and a creator must be defined for the dataset
- Yup validation test that loops through the participant list and each participant's role. If creator and publisher roles are found, the test checks out. Otherwise, error message is displayed.
- Noticed that some translations for error messages could be added/improved

CSCETSIN-564: Validate dataset publisher and creator

---

etsin_finder/frontend/js/components/qvain/utils/formValidation.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js
etsin_finder/qvain_light_utils.py

- The requirements state that it does not need to be a mandatory field
so it is optional now.
- The front end validation does not see it as required anymore and the
backend allows it to be empty.
- Should not have side effects.

CSCETSIN-567: Update field of science to NOT be mandatory.

---

etsin_finder/frontend/js/components/qvain/participants/participantInfo.jsx
etsin_finder/frontend/js/stores/view/qvain.js

- The participant organization field only showed org names in 'und'
language because it is always set in reference data but causes
problems with Qvain where it might not be set. This caused it to not
show anything.
- Added function getOrganizationName that shows it in either the current
language or then just some available language.
- Effects participant mapping in edit.

CSCETSIN-566: Fix org name mapping from Qvain.

---

etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js

- Setting restriction grounds caused an error
- Fixed variable that caused the error (value --> identifier)
- Strangely, the default display values for restriction grounds seem to be working correctly, but are slightly different than the display values retrieved for a restriction grounds object saved in the backend. Investigate?

CSCETSIN-568: Restriction grounds fix

---

etsin_finder/frontend/js/components/qvain/participants/addedParticipants.jsx
etsin_finder/frontend/js/components/qvain/participants/participantInfo.jsx
etsin_finder/frontend/js/components/qvain/utils/formValidation.js
etsin_finder/qvain_light_dataset_schema.py
etsin_finder/qvain_light_utils.py

- Show in the dropdown the values of the current lang, or if not available
show in und, and if not available show in some language that is specified.
Also when selecting an org for a participant it sends to metax all
languages set in reference data.
- Changed the org field to be an object with lang as keys instead of just
a string with the value in und. Also changed validation to support
changes.
- Effects adding participant org in create and edit. Also effects selecting
the org in edit.

CSCETSIN-571: Fix participant org mapping issues.

---

etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
etsin_finder/frontend/js/stores/view/qvain.js
etsin_finder/qvain_light_dataset_schema.py

- If a dataset had title or description in other languages then Qvain
Light overwrote them with only finnish and english. Now all previous
data is stored and only english and finnish ca  be edited.
- Spread the title and description data to a object and edit only fi
and en. In backend validate other than fi and en.
- Effects editing datasets.

CSCETSIN-569: Fix Qvain Light title/description overwrite bug.

---

etsin_finder/frontend/js/components/qvain/general/tooltip.jsx

The user might want to copy text inside the tooltip card. Previously, the tooltip card was closed if the user tried to highlight text (counted as a click). Now, the tooltip is kept open in this case. 
Clicking the tooltip button or outside the tooltip closes the tooltip.

CSCETSIN-559: Keep tooltip open if tooltip card is clicked

---

etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx

Files are more easily identified by their filenames. Thus filename should be used as display value in the IDA selected files list, instead of file title. Simple variable name change.

CSCETSIN-562: Show filename instead of title

---

etsin_finder/frontend/js/components/qvain/files/dataCatalog.jsx

- File origin is a required field and should have an asterisk/star
- Added (*) inside the h3 element that contains "File Origin" / "Tiedoston lähde"
- Moved h3 outside of the Translate element

CSCETSIN-573: Add asterisk to file origin

---

etsin_finder/frontend/js/components/general/button.jsx
etsin_finder/frontend/js/components/general/navigation/dropdownMenu.jsx
etsin_finder/frontend/js/components/qvain/description/descriptionField.jsx
etsin_finder/frontend/js/components/qvain/general/card.jsx
etsin_finder/frontend/js/components/qvain/general/submitResponse.jsx
etsin_finder/frontend/js/components/qvain/index.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- Redesign: Moved publish/update dataset from the bottom of the page to a subheader
- The publish/update button is now always visible on top, using a sticky subheader that follows the user as they scroll the page. Success/loading/error messages are also implemented as part of the sticky subheader. Messages can be closed using a (x) button in the top right corner.
- New containers, close message functionality, lots of .css updates.

 CSCETSIN-550: Added sticky subheader for publishing and updating datasets

---

etsin_finder/frontend/js/components/qvain/general/buttons.jsx

- Having the background-color undefined caused the buttons to default to a gray-ish color
- Added background-color to buttons

CSCETSIN-575: Fix button backgrounds in Safari and Firefox

---

etsin_finder/frontend/js/components/qvain/general/submitResponse.jsx
etsin_finder/frontend/js/components/qvain/index.jsx

First commit (56cf7d5): Submit response moved more to the middle of the screen. Also, "View in Etsin" link added.
Second commit (cef11bf): Reset "Update" button to "Submit" after updating a dataset.
Third commit (ea3ff7c): Added a fade-in effect on the error text after submit, to notify the user that something has actually happened.

CSCETSIN-544: Submit response improvements

---

etsin_finder/frontend/js/components/qvain/files/directoryForm.jsx
etsin_finder/frontend/js/components/qvain/files/fileForm.jsx

- If the file or folder does not have title set, it will put the fileName
or directoryName as default. Also removed the asterisk from directory
description which is not mandatory in Metax.
- In files the fileName is set in no title, and in directories the
directoryName is set if no title. If no description then 'File' or
'Description' is set.
- Effects creating datasets and adding IDA Files/Directories.

CSCETSIN-576: Fix default values for IDA file/folders.

---

etsin_finder/frontend/js/components/qvain/files/dataCatalog.jsx
etsin_finder/frontend/locale/english.js

- File origin change now disallowed either when 1: A file (IDA or external) has been added or 2: The dataset has been saved
- Checking this.props.Stores.Qvain.original to see if dataset has been saved or not
- Small English translation improvement

CSCETSIN-577: Disallow file origin change

---

etsin_finder/frontend/js/components/qvain/description/descriptionField.jsx
etsin_finder/frontend/js/components/qvain/files/dataCatalog.jsx
etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- The user needs to be informed that if they save a dataset with both new and existing IDA files, a new version of the dataset is created, in addition to the already existing one
- New translations, info modal shown the first time the user adds a new file or folder to the dataset
Bonus content:
- Fix missing asterisks that had gone missing at some point

CSCETSIN-499: Show info modal when IDA files/folders are edited in an existing dataset

---

etsin_finder/frontend/js/components/qvain/index.jsx

- Messages from Metax were displayed as [Object object], providing no information
- Login errors are now handled, as well as general Metax errors. Both are displayed in the error header.

CSCETSIN-581: Fix error messages in the submit response

---

etsin_finder/frontend/static/index.template.ejs

- Process.env == production has been changed to process.env['VUE_APP_MATOMO_SITE_ID'], according to instructions.
- Also changed: var _paq = _paq || []; to window._paq = [];
so that all code should be exactly as specified by Shreyas. Previously it was specified according to Matomo's own instructions.

CSCETSIN-590: Fix (hopefully) of Matomo tracking

---

etsin_finder/frontend/js/components/qvain/general/submitResponse.jsx
etsin_finder/frontend/js/components/qvain/index.jsx
etsin_finder/qvain_light_resources.py
etsin_finder/qvain_light_service.py

- Handle cases where user is logged in and has no datasets.
- Backend response handling added. If user's dataset list is empty, but no errors present, an empty response is returned to the frontend. 
- The frontend then handles the empty response correctly: displays 'You have no datasets', instead of an error.
- Important commit is: e1fff76
- Other two commits (ab8653a & efc0fa9) are unrelated marginal improvements.

 CSCETSIN-585: Handle case where user has no datasets

---

etsin_finder/email_utils.py
etsin_finder/resources.py

This commit should fix the issue of Etsin sending email only to the first recipient when you have many addresses. 
The changes were made to function get_email_recipient_addresses so that it returns a list of multiple items, as before it was returning only the first.
Related function & variable names were changed from recipient and address to recipients and addresses. 
Needs to be tested in test-environment later on

Cscetsin 582 email for multiple recipients sent only to first address

---

etsin_finder/frontend/js/components/dataset/content.jsx
etsin_finder/frontend/js/components/dataset/tabs.jsx

- This commit will fix the bug where map and Maps -tab was not show if there was no other info than coordinates.
- It also fixes the bug where Dataset -tab was not shown at all if you have a Map but no Data or Events. Now the Dataset-tab will be displayed as default
- Also, this commit fixes the bug where info from Dataset-tab  was shown under Maps -tab if Maps didn't contain any other information than coordinates.
- Necessary because sometimes user feeds in only a WKT and no place name or other info
- Added this.showMaps() to line 84 in content.jsx and removed this.showData() || this.showEvents() -check from Dataset -tab display in tabs.jsx line 23

Addresses the cases where dataset contains maps but no data or events

---

etsin_finder/frontend/js/components/qvain/files/projectSelector.jsx
etsin_finder/qvain_light_service.py

- Change Metax request URL to be in line with how it is specified in Qvain
- Edited URL variable in qvain_light_service.py. Changed IDA retrieval logic.
- No side effects

CSCETSIN-591: Change Metax request URL

---

etsin_finder/qvain_light_service.py

Revert Metax GET URL changes since they caused project to become unviewable in etsin-stable
- Invalid API calls that worked in development mode but not in stable
- Reverted changes done in CSCETSIN-591

CSCETSIN-682: Revert Metax GET URL changes

---

etsin_finder/qvain_light_service.py

- 682, that reverted 591, was not needed
- This commit is basically a re-commit of 591, that undoes 682
- No side effects

CSCETSIN-684: Revert CSCETSIN-682

---

etsin_finder/frontend/js/components/dataset/agent.jsx

- The use of 'javascript:;' as href is discouraged by the React team and
will be blocked in future versions of React.
- href='javascript:;' ==> href='#0'
- No side effects, only removes warning.

CSCETSIN-686: Changed href of agent ling.

---

etsin_finder/authentication.py
etsin_finder/frontend/js/components/search/index.jsx
etsin_finder/resources.py

Use get_user_csc_name() instead of is_authenticated_CSC_user() to check whether the user is authenticated or not. 
The authentication check was implemented to prevent HAKA users from using Etsin, but was mistakenly implemented using this invalid function.
Bug fix description:
is_authenticated_CSC_user() retrieved samlData that pointed to urn:oid:1.3.6.1.4.1.8057.2.80.26, which, according refers to IDM groups, according to this page:
https://wiki.eduuni.fi/display/cscfairdata/Proxy+Attributes
get_user_csc_name() retrieves saml data that points to urn:oid:1.3.6.1.4.1.16161.4.0.53, which is the CSC username.
Additional content:
- Disabled the 'Include PAS datasets' checkbox

CSCFAIRMETA-106: User cannot login

---

etsin_finder/qvain_light_resources.py
etsin_finder/qvain_light_utils.py

- The issue was causing an unhandled error in the backend when an user
with other groups than IDA groups tried to publish a dataset. This is
due to the check only parsed groups of form 'ASD:123' and when a group
of form 'ASD' came along it caused an Index error when the code tried
to split with ':'.
- Used function from utils to get only IDA groups and added error
handling and logging.
- Should not have side effects.

CSCFAIRMETA-107: Fix index error issue when user with other than IDA groups publisher dataset.

---

etsin_finder/frontend/js/components/frontpage/index.jsx
etsin_finder/frontend/js/stores/domain/auth.js

- The variable that checks whether the user is logged in or not (user.commonName) was removed, since it was unnecessary and caused problems in the backend.
- Changed the variable in question to loggedIn: res.data.is_authenticated. When loggedIn is true, but user.name does not exist, a HAKA account is identified. All CSC users have a user.name.
- Changed some variable definitions and resets for improved code stability & security. Added some comments.

CSCFAIRMETA-141: Login improvement

---

etsin_finder/frontend/js/components/qvain/datasets/table.jsx

- Commit similar to CSCFAIRMETA-23, that fixed dataset titles in the Etsin view page
- Similar syntax, word-break: break-word
- No side effects

CSCFAIRMETA-136: Fix long titles in dataset page

---

etsin_finder/frontend/js/components/dataset/versionselect.jsx

- On the etsin dataset page, the creator's name was visible through the version select dropdown
- Added z-index = 1 to the dropdown, forcing it to stay above the other content
- No side effects. Z-index seems to be functional in combination with tab navigation too.

CSCFAIRMETA-133: Fix version select dropdown visual issue

---

etsin_finder/frontend/js/components/qvain/actors/actorTypeSelect.jsx
etsin_finder/frontend/js/stores/view/qvain.js

- Previously, if the actor name was defined, and the user then switched actor type, the dataset became unpublishable. This was because person and organization are different data types, and the conversion cased errors.
- If the user changes actor type (person <-> organization), the actor details are reset.
- No side effects

CSCFAIRMETA-143: Switching actor type bug

---

.travis-deploy.sh

- Travis fails in .travis-deploy.sh while running
`ansible-galaxy -r requirements.yml install --roles-path=roles` and this
gives the error:
`ansible-galaxy role: error: argument ROLE_ACTION: invalid choice:
'requirements.yml' (choose from 'init', 'remove', 'delete', 'list',
'search', 'import', 'setup', 'login', 'info', 'install')`. This might
be happening because no ansible version is specified and a new release
came 31.10.2019 ansible==2.9.0
- Specified ansible==2.8.6 to see if it fixes the issue.
- Can effect all ansible code.

Fix for Travis failing to run tests.

---

etsin_finder/qvain_light_resources.py
etsin_finder/qvain_light_utils.py

- Remove general IDM project check for 'urn:oid:1.3.6.1.4.1.8057.2.80.26' when trying to publish a dataset. This situation caused problems for users without IDM projects. However, this value is still checked if the user has chosen IDA as catalog.
- Remove the 'urn:oid:1.3.6.1.4.1.8057.2.80.26' check.

CSCFAIRMETA-199: User cannot publish dataset

---

etsin_finder/frontend/js/components/qvain/files/projectSelector.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- This update has already been done in demo. Display a clearer error message if Metax returns 404
- This error means that there are no files in Metax, so the user must first go to IDA and freeze files
- If error message is 404, display text guiding the user to IDA

CSCFAIRMETA-245: Update metax display error

---

etsin_finder/frontend/locale/english.js

- There was an unnecessary text in Qvain-light that was removed.
- Removed the sentence from english.js.

CSCFAIRMETA-123: Fix requested text.

---

etsin_finder/utils.py

- The time format for month was set by accident to %M, which is for
minutes. -> now %m for moth.
source: https://docs.python.org/3/library/time.html#time.strftime
- '%Y-%M-%d %H:%M:%S %z' --> '%Y-%m-%d %H:%M:%S %z'
- Effects timestamp on loggs.

CSCFAIRMETA-198: Fix backend log time format.

---

etsin_finder/frontend/js/components/dataset/accessRights.jsx
etsin_finder/frontend/js/stores/view/access.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- Before the description was taken from the dataset access_rights.description
and it could be whatever the users decides it should be. Now updated to
be fixed strings with a short description of the access right.
- Choose the translation according to the accessRights identifier, If
for some reason the identifier is wrong and not in the constants, then
the value is empty.

CSCFAIRMETA-200: Update AccessRights component description.

---

etsin_finder/qvain_light_service.py

- Datasets were sorted according to date_modified, but unmodified datasets were wrongly displayed at the top of the list, since they didn't have that data value (date_modified)
- Simple fix, changed date_modified to date_created. In the future, date_modified could be displayed in the UI as well.

CSCFAIRMETA-247: Sort datasets according to date created

---

etsin_finder/frontend/js/components/dataset/description.jsx

- Creator name can be too long and extend across the sidebar. This probably wouldn't happen, but you never know.
- Added word-break: break-word as a .CSS property to MainInfo, which is inherited by child elements (including the text display elements).

CSCFAIRMETA-249: Creator name can be too long

---

etsin_finder/finder.py
etsin_finder/frontend/__tests__/qvain.test.jsx
etsin_finder/frontend/js/components/qvain/files/refreshDirectoryModal.jsx
etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx
etsin_finder/frontend/js/components/qvain/general/buttons.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js
etsin_finder/qvain_light_rpc.py
etsin_finder/qvain_light_service.py

- Add a button to existing directories in dataset that allows refreshing the directory contents using a Metax RPC.
- The "Refresh folder content" button is pretty wide. Made some small styling changes in the selected files list to make the buttons behave more nicely in narrow windows.

CSCFAIRMETA-160: Refreshing folder content

---

etsin_finder/frontend/static/index.template.ejs

- Changes needed in order to test the functionality of matomo-test.fairdata.fi
- Added new matomo tracking for test & development Node environments. Reused old code that had been created as inital setup for Matomo, 1 year ago.
- process.env.NODE_ENV === 'development'
- Currently used for local_development & demo  (ToDo in the future: NODE_ENVs should be separated)
- Tracker: matomo-test.fairdata.fi
- siteId: 8
- process.env.NODE_ENV === 'test'
- Currently used for test & stable (ToDo in the future: NODE_ENVs should be separated)
- Tracker: matomo-test.fairdata.fi
- siteId: 3
- process.env.NODE_ENV === 'production'
- Currently used for production
- Tracker: matomo.rahtiapp.fi
- siteId: 3

CSCFAIRMETA-273: Configure matomo-test.fairdata.fi

---

etsin_finder/frontend/js/components/dataset/askForAccess.jsx

- Button is hidden (or more precisely never rendered)  so that users won't click it
- Simple if condition modification
- Button will always be non-existent

CSCFAIRMETA-4: Hide REMS button in frontend

---

etsin_finder/finder.py
etsin_finder/frontend/__tests__/metadataModal.test.jsx
etsin_finder/frontend/js/components/dataset/index.jsx
etsin_finder/frontend/js/components/general/modal.jsx
etsin_finder/frontend/js/components/qvain/files/cumulativeState.jsx
etsin_finder/frontend/js/components/qvain/files/fileForm.jsx
etsin_finder/frontend/js/components/qvain/files/fileSelector.jsx
etsin_finder/frontend/js/components/qvain/files/index.jsx
etsin_finder/frontend/js/components/qvain/files/metadataModal/index.jsx
etsin_finder/frontend/js/components/qvain/files/metadataModal/options.js
etsin_finder/frontend/js/components/qvain/files/metadataModal/select.jsx
etsin_finder/frontend/js/components/qvain/files/refreshDirectoryModal.jsx
etsin_finder/frontend/js/components/qvain/files/response.jsx
etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx
etsin_finder/frontend/js/components/qvain/general/buttons.jsx
etsin_finder/frontend/js/components/qvain/utils/formValidation.js
etsin_finder/frontend/js/components/qvain/utils/object.js
etsin_finder/frontend/js/index.jsx
etsin_finder/frontend/js/stores/view/qvain.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js
etsin_finder/qvain_light_resources.py
etsin_finder/qvain_light_service.py
etsin_finder/qvain_light_utils.py

* Add modal for editing PAS metadata, accessible from file selector and also from editing selected/existing files
* Fixed issue where modal background blur was removed on close attempt even if modal was prevented from actually closing
* Fixed issue where getPath() returned undefined for all falsy values
* Move require('@babel/polyfill') to top of the app entrypoint as suggested in the docs (having it elsewhere caused some issues in testing)

CSCFAIRMETA-103: PAS metadata editing

---

etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx

* CSCFAIRMETA-393: Show "Refresh Directory Content" only for published folders.
* CSCFAIRMETA-394: Show "Refresh Directory Content" only for cumulative datasets.

CSCFAIRMETA-393, CSCFAIRMETA-394: Change when "Refresh Directory Content" button is shown

---

.travis.yml
etsin_finder/frontend/webpack.config.js

The watch target should be used instead:
https://github.com/CSCfi/etsin-finder/blob/test/etsin_finder/frontend/package.json#L20

CSCFAIRMETA-449: Disable watch in webpack.config.js

---

etsin_finder/frontend/js/components/qvain/general/submitResponse.jsx
etsin_finder/frontend/js/components/qvain/index.jsx
etsin_finder/qvain_light_service.py

These bug fixes address issues reported in tickets: CSCFAIRMETA-470, CSCFAIMETA-455, CSCFAIMETA-457 and CSCFAIRMETA-426.
**Not all issues are resolved** since there is a bug in metax related to datasets with files and the use of `?file_details` query parameter. To get the datasets with files working the issue in metax has to be resolved or then Qvain Light has to be refactored to not use the `?file_details` parameter (which could be good but is a large task). The issue in metax will cause it to return: `('{"detail":["failed to publish updates to rabbitmq. request is aborted."]}', 503)` which should at least be handled.
The PR should fix CSCFAIRMETA-426 to the point of showing a metax error since REMS functionality is not implemented in Qvain Light (Before it would crash the page). The PR …

Qvain light bug fixes

---

etsin_finder/rems_service.py
etsin_finder/resources.py

- Dataset page is crashing for datasets with persmission required as access_type
- Add checks for whether rems_api_config is None, thus handling these errors

CSCFAIRMETA-481: Fix bugs

---

etsin_finder/finder.py
etsin_finder/frontend/js/components/qvain/datasets/table.jsx
etsin_finder/frontend/js/components/qvain/deprecatedState.jsx
etsin_finder/frontend/js/components/qvain/files/cumulativeState.jsx
etsin_finder/frontend/js/components/qvain/files/fileSelector.jsx
etsin_finder/frontend/js/components/qvain/files/fixDeprecatedModal.jsx
etsin_finder/frontend/js/components/qvain/files/metadataModal/index.jsx
etsin_finder/frontend/js/components/qvain/files/refreshDirectoryModal.jsx
etsin_finder/frontend/js/components/qvain/files/selectedFiles.jsx
etsin_finder/frontend/js/components/qvain/general/form.jsx
etsin_finder/frontend/js/components/qvain/index.jsx
etsin_finder/frontend/js/components/qvain/utils/responseError.js
etsin_finder/frontend/js/stores/view/qvain.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js
etsin_finder/qvain_light_rpc.py
etsin_finder/qvain_light_service.py

* Show message in top of editor for deprecated datasets.
* Below the message, show button that shows modal for fixing the dataset.
* Dataset fixing modal uses Metax RPC for fixing deprecated datasets.
* Remove metadata editing buttons from dataset files/directories that have been removed.
* Fix: Bug from not taking into account that removed files/folders don't have details.
* Refactor: Use reusable response error handler function to make displaying errors more reliable.

CSCFAIRMETA-244: Allow editing/fixing deprecated datasets in Qvain Light

---

etsin_finder/frontend/__tests__/qvain.test.jsx
etsin_finder/frontend/js/components/qvain/files/externalFileForm.jsx
etsin_finder/frontend/js/components/qvain/files/externalFiles.jsx
etsin_finder/frontend/js/components/qvain/utils/formValidation.js
etsin_finder/frontend/js/stores/view/qvain.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js
etsin_finder/qvain_light_utils.py

By accepting this PR, 
1) Etsin-finder will have new field download_url. which as name suggests, points to downloadable artifacts.
2) Modified translations

CSCFAIRMETA-261: ADD: Download url in qvain-light

---

etsin_finder/frontend/__tests__/rems.test.jsx
etsin_finder/frontend/js/components/dataset/REMSButton.jsx
etsin_finder/frontend/js/components/dataset/askForAccess.jsx
etsin_finder/rems_service.py

- Before the user could click the button once, and then it turned disabled.
Now it is disabled from the start.
- Add check to backend that checks if REMS is enabled. and if not, sets
the application state to 'disabled', which is checked in the frontend
before rendering the button.
How to test:
In your local environment disable REMS by editing app_config, and restart the server.
If you open a dataset that requires permission, the button should be disabled, and by hovering over it should say that you have to log in (if not logged in) or that it is disabled (if logged in).

CSCFAIRMETA-482: Disable REMS button immediately if REMS is not enabled.

---

etsin_finder/frontend/js/components/qvain/files/dataCatalog.jsx
etsin_finder/frontend/js/components/qvain/files/external/externalFiles.jsx
etsin_finder/frontend/js/stores/view/qvain.js
etsin_finder/frontend/locale/finnish.js

**CSCFAIRMETA-527: Fix translation typo**
**CSCFAIRMETA-528: Error handling for remote resource URLs**
- If the URL variables were left empty and then published, the dataset would crash
- Error handling added
**CSCFAIRMETA-529: Uncheck use DOI for remote resources**
- DOI should not be available for remote resources
- Uncheck in local state and in data store

CSCFAIRMETA-32-fixes

---

etsin_finder/cr_service.py
etsin_finder/resources.py

- The use of pref_id in REMS is deprecated and changed to its own REMS
identifier.
- Get catalog items with rems_identifier instead of pref_id. If there is
no catalog item with the identifier, return error. This can happen to
old rems catalogs that don't have the rems_identifier.
- Effects applying access ro REMS catalogs.

CSCFAIRMETA-523: Update pref_id to rems_identifier

---

etsin_finder/frontend/locale/finnish.js
etsin_finder/qvain_light_resources.py
etsin_finder/qvain_light_utils.py

- CSCFAIRMETA-530: Bug fix: Issued date now allows for empty values when updating a dataset, this should be possible if the dataset isn't a DOI dataset
- CSCFAIRMETA-537: Small typo fixes

CSCFAIRMETA-530 & 537: [FIX] Issued date validation fix + typo fixes

---

etsin_finder/frontend/js/components/qvain/files/dataCatalog.jsx
etsin_finder/frontend/js/stores/view/qvain.js

- The app should be aware of the DOI status of an existing dataset
- Add DOI status to the React store, which solves CSCFAIRMETA-532 and CSCFAIRMETA-533 issues where the user could remove issued date and publisher for DOI datasets and update the dataset, causing the app to crash

CSCFAIRMETA-532 & 533: [FIX] Add useDoi to data store

---

etsin_finder/frontend/js/components/qvain/index.jsx
etsin_finder/qvain_light_utils.py

- There was an unhandled error updating older datasets. The cause was some
duplicate code where an object key was eventually not checked if it
existed.
- remove line actor_object["person"]["identifier"] in qvain_light_utils.py
since it is already done in the conditional above. This line caused a
KeyError if the actor person did  not have an identifier. Also refactored
the function to use the 'get' method to get dict attributes because it does
not throw an error and crash if the attribute is not present.
- no side effects

CSCFAIRMETA-549: Fix error updating dataset

---

etsin_finder/frontend/.babelrc
etsin_finder/frontend/__tests__/__snapshots__/filterSection.test.jsx.snap
etsin_finder/frontend/__tests__/__snapshots__/qvain.actors.test.jsx.snap
etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
etsin_finder/frontend/package.json

Improves development experience by giving styled components and the related CSS styles readable names.

CSCFAIRMETA-556: Enable babel-plugin-styled-components

---

etsin_finder/frontend/.babelrc
etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap

The CSS minification enabled by default in the plugin seems to negatively affect some of the styles used in the old filepicker, and it's not entirely obvious why. It's probably better to disable the minification for now, as it wasn't the main point of installing the plugin anyways.

CSCFAIRMETA-556: Disable minification for babel-plugin-styled-components

---

etsin_finder/frontend/js/stores/view/elasticquery.js

- There was the issue where when searching for a phrase, the org faset
would show too many results. This was due to PAS datasets being shown
there as well even though PAA datasets where not selected. This behavior
was caused by the PAS dataset being queried in the search but removed
from the aggregated buckets, thus not showing the datasets, but appearing
in the result count. Also The user had no way of searching an org in the
search.
- PAS datasets are being filtered in the initial query instead of being
excluded from the aggregated results. Added the organization_name*^3
to the fields to be queried in the search. This way the users can
search for an organization name and get relevant results to that. To
get only the results from a particular org it is still recommended to
use the org …

CSCFAIRMETA-555: Fix issues related to PAS datasets in Etsin search

---

etsin_finder/frontend/js/components/dataset/sidebar/index.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- The subject heading words where previously mixed with keywords and
only represented as text. Now they have their own field and they are
links to the correct koko ontology.
- Created new field for the subject headings if present.

CSCFAIRMETA-514: Add subject heading links

---

etsin_finder/frontend/js/layout/header.jsx

A nav element in the header had a fixed width that was smaller than the size of its contents. This caused navigation elements to overlap when window width was between 992 and 1200 px and language was set to Finnish.

CSCFAIRMETA-649: Fix overlapping navigation buttons

---

etsin_finder/authentication.py
etsin_finder/cr_service.py
etsin_finder/frontend/js/components/dataset/description.jsx
etsin_finder/qvain_light_utils.py
etsin_finder/resources.py

* Limit access to draft dataset and related Etsin views so only the owner can access them
* Also fixes bug where unpublished new version fails in Etsin due to not being in its own dataset_version_set

CSCFAIRMETA-588: Only owner can view draft in Etsin

---

etsin_finder/frontend/js/layout/cookiesNotification.jsx
etsin_finder/frontend/js/layout/index.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

Implement a notification for describing cookie usage on Etsin and Qvain Light.
Cookie acceptance is saved to local storage and the notification will not be displayed if acceptance is present in the local storage.
**Note:** User acceptance should be refactored when integrated to Matomo and SSO. Currently acceptance is saved for the sake of not displaying the notification every time when a user visits the site. 
- Finnish translations should be approved before deploying to production

CSCFAIRMETA-651: Implement cookie notification message

---

etsin_finder/frontend/js/components/dataset/sidebar/special/citation.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

Remove any extra commas from citation, included by missing elements (e.g. publishing date).
If publishing date is not available, include additional message about it bellow the citation.

CSCFAIRMETA-359: Fix citation formatting

---

etsin_finder/frontend/js/components/dataset/sidebar/special/citation.jsx
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js

- Previously, the timestamp "modified" (related to the metadata) was specified in the citation, which was often empty
- Now, issued date is instead defined, which is much more useful for researchers and users
- Issued date is (for instance) required for all DOI datasets
- Related to previous PR https://github.com/CSCfi/etsin-finder/pull/485

CSCFAIRMETA-652: [FIX] Change citation/reference to include issued date

---

etsin_finder/frontend/__tests__/__snapshots__/qvain.files.test.jsx.snap
etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
etsin_finder/frontend/__tests__/qvain.test.jsx
etsin_finder/frontend/js/components/qvain/description/index.jsx
etsin_finder/frontend/js/components/qvain/description/languageField.jsx
etsin_finder/frontend/js/components/qvain/general/searchSelect.jsx
etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
etsin_finder/frontend/js/components/qvain/utils/select.js
etsin_finder/frontend/js/stores/view/qvain.js
etsin_finder/frontend/locale/english.js
etsin_finder/frontend/locale/finnish.js
etsin_finder/qvain_light_dataset_schema.py
etsin_finder/qvain_light_utils.py

- Add field for dataset language
Language select fetches options from Metax when user types to search in select component, as there is thousands of language choices. Tested with submitting a new dataset and editing an existing dataset.
Minor changes:
- `qvain/general/searchSelect.jsx` refactored
- Select options sorted alphabetically by label (currently in frontend, is there a param to do this in Metax, probably more efficient to do this in backend)

CSCFAIRMETA-458: add field for Language

---

etsin_finder/frontend/js/layout/index.jsx

This commit hides the cookie notification, implementation is still
present in the codebase. This modification should be reverted when we
want to display the cookie notification.

CSCFAIRMETA-651 Hide cookie notification

---

etsin_finder/frontend/__tests__/qvain.actors.test.jsx
etsin_finder/frontend/js/components/qvain/actors/addedActors.jsx

- Actors are mandatory (at least one actor) and should be displayed as such
- Display hover tooltip component also for the actors header
- Add asterisk

CSCFAIRMETA-546: [ADD] Missing asterisk & hover tooltip for actors

---

etsin_finder/frontend/__tests__/authStore.test.jsx
etsin_finder/frontend/__tests__/rems.test.jsx
etsin_finder/frontend/js/components/qvain/datasets/removeModal.jsx
etsin_finder/frontend/js/stores/domain/auth.js

* Reset store state before each test
* Fix delayed test failures that were counted as passing
* Refactor tests to use async functions
* Add test to make sure user fields are filled in properly
* Hide console.error logging during tests

CSCFAIRMETA-678: Fix Auth store tests

---

etsin_finder/frontend/js/stores/view/qvain.js

- This should not require separate definition (i.e. should not require user manually selecting the date)
- Now: if undefined, then today's date will be used (using the moment() library)
- Do not set the date by default using moment(), since that would cause snapshot issues
- Default must be undefined, and then later defined. Defined when title is set.

CSCFAIRMETA-679: [FIX] Use today's date for publishing by default

---

etsin_finder/frontend/js/components/qvain/actors/field/index.jsx
etsin_finder/frontend/js/components/qvain/actors/modal/roleCheckbox.jsx
etsin_finder/frontend/js/components/qvain/description/keywordsField.jsx
etsin_finder/frontend/js/components/qvain/description/otherIdentifierField.jsx
etsin_finder/frontend/js/components/qvain/general/addButton.jsx
etsin_finder/frontend/js/components/qvain/general/buttons.jsx
etsin_finder/frontend/js/components/qvain/general/card.jsx
etsin_finder/frontend/js/components/qvain/general/durationpicker.jsx
etsin_finder/frontend/js/components/qvain/general/fieldListAdd.jsx
etsin_finder/frontend/js/components/qvain/general/form.jsx
etsin_finder/frontend/js/components/qvain/general/modalReferenceInput.jsx
etsin_finder/frontend/js/components/qvain/temporalAndSpatial/spatial/form/SpatialArrayInput.jsx

- Make margins more consistent in the UI
- Use `display: block` for inputs to allow margins to collapse
- Allow sticky header to grow vertically when needed

CSCFAIRMETA-675: Improve margins

---

requirements.txt

Needed by https://github.com/CSCfi/etsin-ops/pull/28 to support `SameSite=None`

CSCFAIRMETA-706: Update werkzeug version

---

etsin_finder/frontend/__tests__/__snapshots__/qvain.test.jsx.snap
etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
etsin_finder/frontend/js/components/general/navigation/maybeNavLink.jsx
etsin_finder/frontend/js/components/general/navigation/mobileNavi.jsx
etsin_finder/frontend/js/components/general/navigation/settings.jsx
etsin_finder/frontend/js/components/qvain/datasets/dataset.jsx
etsin_finder/frontend/js/components/qvain/datasets/index.jsx
etsin_finder/frontend/js/components/qvain/datasets/table.jsx
etsin_finder/frontend/js/components/qvain/editor/submitButtons.jsx
etsin_finder/frontend/js/components/qvain/files/metadataModal/index.jsx
etsin_finder/frontend/js/components/qvain/files/response.jsx
etsin_finder/frontend/js/components/qvain/general/submitResponse.jsx
etsin_finder/frontend/js/components/qvain/main/index.jsx
etsin_finder/frontend/js/layout/content.jsx
etsin_finder/frontend/js/stores/domain/auth.js
etsin_finder/frontend/js/stores/domain/env.js
etsin_finder/frontend/js/stores/view/elasticquery.js
etsin_finder/frontend/js/stores/view/qvain.actors.js
etsin_finder/frontend/package.json
etsin_finder/frontend/webpack.config.js
etsin_finder/frontend/webpack.prod.js

* Read variables from `frontend/.env` if it exists using `dotenv-webpack` plugin
* Use REACT_APP_ETSIN_HOST, REACT_APP_QVAIN_HOST env variables for redirection between Etsin and Qvain
* When REACT_APP_QVAIN_HOST is defined and different from the Etsin host, `/qvain` is redirected there
* Add `Env.getQvainUrl()` that adds the `/qvain` prefix and/or the correct host when needed
* Add `Env.getEtsinUrl()` that adds Etsin host when needed
* Unless configured in `.env` to have separate hosts for Etsin and Qvain, Etsin should work as before
* Known issues:
* Window title is the same for Etsin and Qvain
* Navigation bar is the same for Etsin and Qvain
* Qvain "Preview in Etsin" link for drafts does not work properly if user is not logged into Etsin

CSCFAIRMETA-706: Front-end support for running Etsin and Qvain Light in separate domains

---

etsin_finder/frontend/__tests__/__snapshots__/qvain.actors.test.jsx.snap
etsin_finder/frontend/__tests__/qvain.actors.test.jsx
etsin_finder/frontend/js/stores/view/qvain.actors.js

Fixes issue where Qvain Light doesn't load email addresses for manually added organizations.

CSCFAIRMETA-721: Fix missing organization email on dataset load

---

etsin_finder/frontend/package-lock.json

- After "style-loader" was updated to version "^1.2.1", the package-lock.json file will change when running npm install --only=production in test, stable, demo, and production.
- This needs to be reflected in the repository, otherwise Ansible will find local changes in etsin-test and other environments and stop its script execution
What I did:
- git checkout test
- git pull
- git reset --hard origin/test
- git checkout -b CSCFAIRMETA-690-package-lock
- SSH into local machine as etsin-user
- cd ../frontend
- rm -rf node_modules
- npm prune
- npm install --only=production
... Result is this PR. These changes look similar to what was found in etsin-test after Travis was run.

CSCFAIRMETA-690: [FIX] Update package-lock.json

---

etsin_finder/frontend/js/components/general/skipToContent.jsx
etsin_finder/frontend/js/components/qvain/editor/dataset.jsx
etsin_finder/frontend/js/components/qvain/editor/editor.styled.jsx
etsin_finder/frontend/js/components/qvain/main/index.jsx

* Add hidden disabled button to disable implicit submit for the dataset form
* Fix bound setFocusOnSubmitButton having wrong name
* Add type="button" to STSD (SkipToSubmitDataset) and STC (SkipToContent) components
* Unabbreviate STSD and STC component names to make their purpose clearer

CSCFAIRMETA-727: Prevent enter in input from causing form submission

---

etsin_finder/frontend/js/stores/view/qvain.js

1) Setting DOI date to today's date as default was implemented here (defined in setTitle()):
https://github.com/CSCfi/etsin-finder/pull/530
2) ... but the direct call to setTitle(), from handleTitleChange(), was removed here:
https://github.com/CSCfi/etsin-finder/commit/85d3ecf885493948b9b0eb0b414e9d201d40922e#diff-c6721e58eaa8c05a170fb0e6a8ae449eL29
3) Thus, the DOI date setting functionality was never called anymore -> Moved it to setDataCatalog()
Bonus: Looks like setTitle() and setDescription() are not used anymore. Removed these functions.

CSCFAIRMETA-679: [FIX] DOI date settings, remove obsolete functions

---

etsin_finder/frontend/static/index.template.ejs
etsin_finder/views.py

* Use Flask render_template to set title and meta description for Etsin/Qvain
* Because the etsin_app cookie is not available on the first request, X-Etsin-App header is used for identifying the app

CSCFAIRMETA-720: Set title based on app

---

etsin_finder/frontend/js/components/dataset/formatselect.jsx
etsin_finder/frontend/js/components/dataset/versionselect.jsx

* Toggle isFocused when dropdown is toggled to bypass Firefox not triggering onFocus when the dropdown controller is clicked

CSCFAIRMETA-486: Fix version/download dropdowns not working in Firefox on macOS

---

etsin_finder/authentication_fairdata_sso.py
etsin_finder/views.py

* Append path from the relay login parameter to the redirect_url parameter required by SSO
* Relay path may contain query parameters
* Old proxy still uses the RelayState parameter provided by the saml2 library

CSCFAIRMETA-755: Fix login relay parameter for SSO

---

etsin_finder/authentication_direct_proxy.py
etsin_finder/views.py

- This is mostly cleanup, the actual support is handled elsewhere, through correct settings in app_config
- Removal of functions that are neither used by the old proxy login nor the new SSO login
- The changes in etsin_finder/authentication_direct_proxy.py will ensure that proxy login works

CSCFAIRADM-407: [FIX] Support old login

---

etsin_finder/frontend/js/components/dataset/data/tableItem.jsx

- Add 'word-break: break-all' to break the long filenames

CSCFAIRMETA-722-Long-filenames

---

etsin_finder/authentication.py

- Better to check for "IDA01:" instead of "IDA", since there might be cases where projects are named "IDA...".
- "IDA01" separates IDA projects from IDM groups

CSCFAIRMETA-779: [FIX] Restrict IDA project check to "IDA01:"

---

etsin_finder/app_config.py

This changes the backend to use config from the app context instead of reading and parsing the app_config file every time some configuration value is needed. For some endpoints, such as /user (which read the config almost 30 times per request), this is a significant reduction in overhead.

CSCFAIRMETA-753: Use config from app context when available

---

etsin_finder/frontend/package-lock.json

- MobX updated, but not reflected in package-lock.json
- ... causing Ansible deployments to fail
- This PR fixes the details in package-lock.json

[FIX] Update package-lock.json to reflect new version of Mobx

---

etsin_finder/frontend/js/layout/cookiesNotification.jsx

- For accessibility reasons, improve the color contrast to > 4.5. Also
some linting and formatting.
- Change color of text to #0075a3

CSCFAIRMETA-673: Improve color contrast of cookie notification link

---

etsin_finder/app_config.py
etsin_finder/authentication_fairdata_sso.py
etsin_finder/frontend/js/components/general/keepAlive/index.jsx
etsin_finder/frontend/js/components/general/navigation/loginButton.jsx
etsin_finder/saml_config.py
etsin_finder/views.py

- Enable both SSO or SAML login, depending on app config
- SSO can be force enabled by visiting the hidden URL endpoint `?sso_authentication=true`
- Requires https://github.com/CSCfi/etsin-ops/pull/46
- SSO checks for active sessions even if not enabled

CSCFAIRMETA-821: Refactor SSO & SAML

---

etsin_finder/frontend/js/components/search/filterResults/filterSection.jsx

- Add a outline to elements in the filter when they are in focus.
- Remove the 'outline: none;' in css for the button.

CSCFAIRMETA-665: Add focus indicator to filter items.

---

etsin_finder/authorization.py

- Check removed datasets in query
- Such datasets should be displayed as tombstone pages

CSCFAIRMETA-838: Removed datsets not visible

---

etsin_finder/app.py
etsin_finder/app_config.py
etsin_finder/finder.py
etsin_finder/flags.py
etsin_finder/frontend/__tests__/__snapshots__/qvain.test.legacy.jsx.snap
etsin_finder/frontend/__tests__/cumulativeState.test.jsx
etsin_finder/frontend/__tests__/download.test.jsx
etsin_finder/frontend/__tests__/general.flaggedComponent.test.jsx
etsin_finder/frontend/__tests__/metadataModal.legacy.test.jsx
etsin_finder/frontend/__tests__/metadataModal.test.jsx
etsin_finder/frontend/__tests__/qvain.accessType.test.jsx
etsin_finder/frontend/__tests__/qvain.actors.test.jsx
etsin_finder/frontend/__tests__/qvain.files.legacy.jsx
etsin_finder/frontend/__tests__/qvain.files.test.jsx
etsin_finder/frontend/__tests__/qvain.metadata.store.test.js
etsin_finder/frontend/__tests__/qvain.test.jsx
etsin_finder/frontend/__tests__/qvain.test.legacy.jsx
etsin_finder/frontend/__tests__/qvainPas.legacy.test.jsx
etsin_finder/frontend/__tests__/qvainPas.test.jsx
etsin_finder/frontend/__tests__/removeModal.test.jsx
etsin_finder/frontend/__tests__/submitButtons.test.jsx
etsin_finder/frontend/js/components/general/flaggedComponent.jsx
etsin_finder/frontend/js/stores/domain/env.flags.js
etsin_finder/frontend/js/stores/domain/env.js
etsin_finder/resources.py
tests/basetest.py
tests/test_flags.py
tests/test_request_utils.py

* Add list of supported flags in `flags.py`
* Add FLAGS dict to app_config, used by both backend and frontend
* Support enabling flags by group, e.g. `GROUP: True` enables `GROUP.FLAG1`, `GROUP.FLAG2`
* Add FlaggedComponent helper for creating flagged frontend components
* Convert DOWNLOAD_API_V2.ENABLED and metaxApiV2 to new flag implementation
* Add global development helpers for overriding frontend flags: setFlag, cleanupFlags, flagEnabled, getFlags, resetFlags

CSCFAIRMETA-834: Feature flags

---

etsin_finder/frontend/package-lock.json

This PR is similar to the previous https://github.com/CSCfi/etsin-finder/pull/586
Travis deployment fails ( https://travis-ci.com/github/CSCfi/etsin-finder/jobs/462225761 ) ... due to differences in package-lock.json, related to recent updates to package.json:
- CSCFAIRMETA-28: https://github.com/CSCfi/etsin-finder/pull/654
- CSCFAIRMETA-805: https://github.com/CSCfi/etsin-finder/commit/833e39bad0ef9da250c44dcb318f6e1efc1855f2
- CSCFAIRMETA-831: https://github.com/CSCfi/etsin-finder/pull/653/
What was done:
- In local env, `git checkout test && git pull`
- In local env, `npm prune && npm install --only=production`
- Result: this PR

Travis: Update package-lock.json

---

etsin_finder/frontend/package-lock.json

This PR is similar to these two previous ones:
- https://github.com/CSCfi/etsin-finder/pull/586
- https://github.com/CSCfi/etsin-finder/pull/663
Travis deployment fails:
https://travis-ci.com/github/CSCfi/etsin-finder/jobs/474289763
… due to changes in package.json and package-lock.json, merged to test here:
https://github.com/CSCfi/etsin-finder/commit/9b5b72360f8c3669e061a3f25843573a89220a8b
What was done:
- `git checkout test && git pull`
- `cd /etsin_finder/frontend`
- `npm prune`
- `npm install --only=production`

Fix package-lock.json to reflect new changes

---

etsin_finder/frontend/js/stores/view/locale.js

Fixes an issue where only the first character of the name was displayed for items in `Spatial coverage` list.

CSCFAIRMETA-909: Fix only first character of spatial being shown

---

etsin_finder/frontend/js/components/general/loader.jsx
etsin_finder/frontend/js/components/general/navigation/loginButton.jsx

When user clicked login and then returned to previous page, if this didn't cause a page reload, the login spinner was stuck on.
This also removes transitions that caused some visual bugs in Loader.

CSCFAIRMETA-914: Fix login spinner getting stuck

---

.travis.yml
etsin_finder/frontend/__tests__/__testdata__/dataset.att.js
etsin_finder/frontend/__tests__/combined/qvain/a11y/qvain.editor.a11y.test.jsx
etsin_finder/frontend/__tests__/combined/qvain/metadataModal.test.jsx
etsin_finder/frontend/js/components/qvain/fields/licenses/restrictionGrounds.jsx
etsin_finder/frontend/package-lock.json
etsin_finder/frontend/package.json

* Add jest-axe tests for Qvain editor
* Add missing label to restriction grounds
* Update react-modal
* Use node v12.x.x for travis (some jest-axe dependency didn't work with v8 that was used previously)

CSCFAIRMETA-925: Qvain editor accessibility tests

---

etsin_finder/frontend/js/components/qvain/general/card/index.jsx
etsin_finder/frontend/js/components/qvain/views/datasets/index.jsx
etsin_finder/frontend/js/components/qvain/views/editor/header.jsx

* Rename SubHeader to PageTitle to make its purpose clearer
* Remove extra h1 from datasets page title
* Remove unintentional margin from below the page title block

CSCFAIRMETA-944: Unify Qvain page title styles

---

etsin_finder/frontend/__tests__/utils/cite.test.js
etsin_finder/frontend/__tests__/utils/idnToLink.test.jsx
etsin_finder/frontend/js/components/dataset/citation/cite/apa.js
etsin_finder/frontend/js/components/dataset/citation/cite/chicago.js
etsin_finder/frontend/js/components/dataset/citation/cite/citationBuilder.js
etsin_finder/frontend/js/components/dataset/citation/cite/index.js
etsin_finder/frontend/js/components/dataset/citation/cite/mla.js
etsin_finder/frontend/js/components/dataset/citation/cite/utils.js
etsin_finder/frontend/js/utils/idnToLink.jsx

* Use URL for DOI in all citation styles
* Use URL for urn:nbn:fi citations in all citation styles
* Change e.g. `cite.apa(dataset)` to `c(dataset)` in tests to avoid prettier splitting it into multiple lines

CSCFAIRMETA-906: Always use URL for DOI/URN citations

---

etsin_finder/frontend/__tests__/combined/etsin/externalResources.test.jsx
etsin_finder/frontend/js/components/dataset/data/externalResources/index.jsx
etsin_finder/frontend/js/components/dataset/data/externalResources/resourceItem.jsx

* Remote resources tab will show only the common source button when all access urls are same
* Justify category column right when there are no dl/source buttons

CSCFAIRMETA-990: Hide source buttons when there is a common source

---

etsin_finder/frontend/webpack.dev.js

This should reduce webpack-dev-server memory usage by not creating a new file each time code changes.

CSCFAIRMETA-1034: Disable hash names in development

---

docker-compose-with-nginx.yml
docker-compose.yml

- Add in both docker-compose files
Additional fixes:
- Also add tests as a volume if running the standalone version (with nginx for etsin-qvain only)
- Use basic nginx image, no need for using a special nginx version/image

CSCFAIRADM-590: Add memcached (to Docker)

---

etsin_finder/frontend/__tests__/stores/view/qvain.spatial.test.js
etsin_finder/frontend/__tests__/stores/view/usedEntities.test.js
etsin_finder/frontend/js/stores/view/qvain/qvain.spatials.js
etsin_finder/frontend/js/stores/view/qvain/qvain.usedEntities.js

fix for provenance not loading spatials and usedEntities when editing a existing dataset.

CSCFAIRMETA-1119 fix for provenance not loading spatials and usedEntities

---

etsin_finder/frontend/js/components/qvain/fields/files/ida/selectedItemsDropdown.jsx

fixed an error where pen icon's color did not update when adding or removing metadata

CSCFAIRMETA-1122 pen icon does not update

---

etsin_finder/frontend/__tests__/combined/etsin/download.test.jsx
etsin_finder/frontend/js/components/dataset/content.jsx
etsin_finder/frontend/js/components/dataset/data/idaResources/downloadActions.js
etsin_finder/frontend/js/components/dataset/data/idaResources/index.jsx
etsin_finder/frontend/js/components/dataset/data/index.jsx
etsin_finder/frontend/js/stores/view/datasetquery.js
etsin_finder/frontend/locale/english/index.js

* Fix download buttons not being disabled for drafts
* Move generation of allowDownload and downloadAllText to downloadActions
* Remove redundant data prop

CSCFAIRMETA-1138: Disable download buttons for drafts

---

etsin_finder/frontend/__tests__/combined/qvain/__snapshots__/qvain.files.test.jsx.snap
etsin_finder/frontend/__tests__/stores/view/qvain.restrictionGrounds.test.js
etsin_finder/frontend/__tests__/utils/utils.handleSubmit.test.js
etsin_finder/frontend/js/components/qvain/general/errors/validationError.jsx
etsin_finder/frontend/js/components/qvain/general/header/tooltipHoverOnSave.jsx
etsin_finder/frontend/js/components/qvain/utils/handleSubmit.js
etsin_finder/frontend/js/stores/view/qvain/qvain.accessType.js
etsin_finder/frontend/js/stores/view/qvain/qvain.embargoExpDate.js
etsin_finder/frontend/js/stores/view/qvain/qvain.license.js
etsin_finder/frontend/js/stores/view/qvain/qvain.restrictionGrounds.js
etsin_finder/frontend/js/stores/view/qvain/qvain.submit.schemas.js
etsin_finder/schemas/qvain_dataset_schema.py
etsin_finder/schemas/qvain_dataset_schema_v2.py
etsin_finder/utils/qvain_utils.py
tests/frontend_test_data.py
tests/test_qvain_utils.py

CSCFAIRMETA-1160: Refactor saving access rights
* Save access rights (license, access type, restriction grounds, embargo) in Metax JSON format
* Use separate frontend schemas for Qvain and Metax data models
* Fix errors when loading draft that does not have access_rights
* Show errors that aren't translation keys properly in submit buttons

CSCFAIRMETA-1160: Refactor saving access rights
